const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // --- build options: -Dlayout=L1 -Dstrat=naive (verticals) or -Dstage=7 (arc) ---
    // Exactly one selector: -Dlayout+ -Dstrat is the layout-verticals interface;
    // -Dstage selects an arc stage (src/stages/, untouched history). If both are
    // given, -Dstage wins (arc compatibility) with a build-time warning.
    const layout_opt = b.option([]const u8, "layout", "layout id, e.g. L1 (needs -Dstrat)");
    const strat_opt = b.option([]const u8, "strat", "strategy name, e.g. naive | simd | par | halide_a");
    const stage_opt = b.option([]const u8, "stage", "arc stage number 1..11");
    const mode_str = b.option([]const u8, "mode", "play | bench | audit") orelse "play";
    const death_str = b.option([]const u8, "death", "death pattern: natural | half | alternating") orelse "natural";
    if (!std.mem.eql(u8, death_str, "natural") and !std.mem.eql(u8, death_str, "half") and !std.mem.eql(u8, death_str, "alternating")) {
        std.debug.panic("invalid -Ddeath='{s}' (natural|half|alternating)", .{death_str});
    }

    const mode: Mode = blk: {
        if (std.mem.eql(u8, mode_str, "play")) break :blk .play;
        if (std.mem.eql(u8, mode_str, "bench")) break :blk .bench;
        if (std.mem.eql(u8, mode_str, "audit")) break :blk .audit;
        std.debug.panic("invalid -Dmode='{s}' (play|bench|audit)", .{mode_str});
    };
    const mode_enum: Mode = mode;

    // Resolve the selection to a canonical sim name + display label.
    // Names: "stage1".."stage11" (arc) and "L<layout>.<strat>" (verticals);
    // main.zig's comptime registry must have an arm for each.
    var name: []const u8 = undefined;
    var label: []const u8 = undefined;
    if (stage_opt) |stage_str| {
        if (layout_opt != null or strat_opt != null)
            std.debug.print("warning: both -Dstage and -Dlayout/-Dstrat given; -Dstage wins\n", .{});
        const stage: u32 = std.fmt.parseInt(u32, stage_str, 10) catch {
            std.debug.panic("invalid -Dstage='{s}' (expected integer)", .{stage_str});
        };
        // Arc invariant (layout-verticals.md §8.1): stages are natural-only
        // and are never edited; adversarial death regimes are layouts-only.
        if (!std.mem.eql(u8, death_str, "natural"))
            std.debug.panic("-Ddeath={s} requires a layout (-Dlayout/-Dstrat); arc stages are natural-only", .{death_str});
        name = b.fmt("stage{d}", .{stage});
        label = arcLabel(stage) orelse
            std.debug.panic("invalid -Dstage={d} (expected 1..11)", .{stage});
    } else {
        const layout = layout_opt orelse "L1";
        const strat = strat_opt orelse "naive";
        name = b.fmt("{s}.{s}", .{ layout, strat });
        label = stratLabel(layout, strat) orelse
            std.debug.panic("invalid -Dlayout='{s}' -Dstrat='{s}' (see strat_labels in build.zig)", .{ layout, strat });
    }

    const opts = b.addOptions();
    opts.addOption([]const u8, "name", name);
    opts.addOption([]const u8, "label", label);
    // The golden files are generated by the reference sim only: the L1 naive
    // strategy (= arc stage 1's code, moved). Arc stage 1 also regenerates,
    // preserving main's behavior while the arc is the only consumer.
    opts.addOption(bool, "is_reference", std.mem.eql(u8, name, "L1.naive") or std.mem.eql(u8, name, "stage1"));
    opts.addOption([]const u8, "death", death_str);
    opts.addOption(Mode, "mode", mode_enum);

    // --- raylib C library (compiled directly; raylib-zig build is broken on 0.17-dev) ---
    const raylib_lib = addRaylib(b, target, optimize);

    // --- main exe ---
    const exe = b.addExecutable(.{
        .name = "dod-particles",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    // --- stb_image_write (linked unconditionally: --record is a bench flag on
    // every sim, not a stage-11 special case; one small C file) ---
    exe.root_module.addCSourceFile(.{
        .file = b.path("src/stb_impl.c"),
        .flags = &.{"-std=c11"},
    });
    exe.root_module.addIncludePath(b.path("vendor/stb"));

    exe.root_module.addOptions("options", opts);
    exe.root_module.addImport("raylib", raylib_module: {
        const rl_mod = b.createModule(.{
            .root_source_file = b.path("src/bindings/raylib.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        });
        rl_mod.linkLibrary(raylib_lib);
        break :raylib_module rl_mod;
    });

    b.installArtifact(exe);

    const run = b.addRunArtifact(exe);
    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run.step);

    // --- unit tests (render_opt's rasterizer byte-equivalence proof) ---
    const unit_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/test_root.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    unit_tests.root_module.addOptions("options", opts); // config.zig imports options (death pattern)
    const run_tests = b.addRunArtifact(unit_tests);
    const test_step = b.step("test", "Run unit tests (render_opt rasterizer equivalence)");
    test_step.dependOn(&run_tests.step);
}

pub const Mode = enum { play, bench, audit };

/// Arc stage number -> HUD label (arc names preserved; -Dstage selects the
/// arc sims in src/stages/, untouched).
fn arcLabel(stage: u32) ?[]const u8 {
    return switch (stage) {
        1 => "Stage 1: naive",
        2 => "Stage 2: hot/cold",
        3 => "Stage 3: SoA",
        4 => "Stage 4: compact",
        5 => "Stage 5: sort-by-kind",
        6 => "Stage 6: SIMD",
        7 => "Stage 7: align",
        8 => "Stage 8: alloc",
        9 => "Stage 9: synthesis",
        10 => "Stage 10: rasterizer",
        11 => "Stage 11: record",
        else => null,
    };
}

const StratEntry = struct { layout: []const u8, strat: []const u8, label: []const u8 };

/// The strategy registry (layout-verticals.md §9): every buildable
/// (layout, strat) and its HUD label. main.zig's comptime map must have an
/// arm for each. Layouts land one vertical at a time.
const strat_labels = [_]StratEntry{
    .{ .layout = "L1", .strat = "naive", .label = "L1.naive (AoS full-field baseline; = arc stage 1)" },
    .{ .layout = "L1", .strat = "naive_r1", .label = "L1.naive_r1 (naive + optimized splat render)" },
    .{ .layout = "L1", .strat = "par", .label = "L1.par (multicore range-partitioned, two-phase)" },
};

fn stratLabel(layout: []const u8, strat: []const u8) ?[]const u8 {
    for (strat_labels) |s|
        if (std.mem.eql(u8, s.layout, layout) and std.mem.eql(u8, s.strat, strat)) return s.label;
    return null;
}

fn addRaylib(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) *std.Build.Step.Compile {
    const c_flags = &.{
        "-std=c11",
        "-DPLATFORM_DESKTOP",
        "-DGRAPHICS_API_OPENGL_33",
        // Disable raylib's image-export helpers (ExportImage* — unused by us).
        // They embed stb_image_write with IMPLEMENTATION inside rtextures.c,
        // which would collide with our own src/stb_impl.c (stages 10/11).
        "-DSUPPORT_IMAGE_EXPORT=0",
        "-ObjC",
    };

    const sources = [_][]const u8{
        "rcore.c",
        "rglfw.c",
        "rshapes.c",
        "rtextures.c",
        "rtext.c",
        "rmodels.c",
    };

    const lib = b.addLibrary(.{
        .name = "raylib",
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
        .linkage = .static,
    });
    inline for (sources) |s| {
        lib.root_module.addCSourceFile(.{
            .file = b.path("vendor/raylib/src/" ++ s),
            .flags = c_flags,
        });
    }
    lib.root_module.addIncludePath(b.path("vendor/raylib/src"));
    lib.root_module.addIncludePath(b.path("vendor/raylib/src/external/glfw/include"));

    lib.root_module.linkFramework("Cocoa", .{});
    lib.root_module.linkFramework("IOKit", .{});
    lib.root_module.linkFramework("CoreVideo", .{});
    lib.root_module.linkFramework("CoreFoundation", .{});
    lib.root_module.linkFramework("OpenGL", .{});

    b.installArtifact(lib);
    return lib;
}
