const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // --- build options: -Dlayout=L1 -Dstrat=naive (the layout verticals) ---
    // The arc (src/stages/) is retired as a build target — relocated to
    // .scratch/orig/ as reference history (optimization-framework §11/§16.1).
    // -Dstage is gone; its cells are scavenged where useful
    // (L1.B1.w1-autovec.w2-simple == arc stage 1's step).
    const layout_opt = b.option([]const u8, "layout", "layout id, e.g. L1 (needs -Dstrat)");
    const strat_opt = b.option([]const u8, "strat", "strategy name, e.g. B1.w1-autovec.w2-simple");
    const halide_variant_opt = b.option([]const u8, "halide_variant", "Halide sweep candidate id (links a pre-generated out/halide/<strat>_<id>.a)");
    const mode_str = b.option([]const u8, "mode", "play | bench | audit") orelse "play";
    // Death model (optimization-framework.md §7): competing risks. `-Ddeath`
    // is the per-frame accident rate q (a float, default 0 = natural). The
    // old `natural | half | alternating` enum is retired; natural ≡ q=0
    // comptime-prunes to the plain age test, half is now q≈0.5 of the
    // competing-risks family, alternating is gone (the hybrid's high-q end
    // covers it).
    const death_q = b.option(f64, "death", "per-frame accident rate q (natural = 0; e.g. 0.5)") orelse 0.0;
    if (!std.math.isFinite(death_q) or death_q < 0.0 or death_q >= 1.0)
        std.debug.panic("invalid -Ddeath={d} (expect 0 <= q < 1)", .{death_q});

    const mode: Mode = blk: {
        if (std.mem.eql(u8, mode_str, "play")) break :blk .play;
        if (std.mem.eql(u8, mode_str, "bench")) break :blk .bench;
        if (std.mem.eql(u8, mode_str, "audit")) break :blk .audit;
        if (std.mem.eql(u8, mode_str, "manifest")) break :blk .manifest;
        std.debug.panic("invalid -Dmode='{s}' (play|bench|audit|manifest)", .{mode_str});
    };
    const mode_enum: Mode = mode;

    // Resolve the selection to a canonical sim name + display label.
    // Names are "L<layout>.<strat>"; main.zig's comptime registry must have
    // an arm for each.
    var name: []const u8 = undefined;
    var label: []const u8 = undefined;
    var layout_sel: ?[]const u8 = null;
    var strat_sel: ?[]const u8 = null;
    {
        const layout = layout_opt orelse "L1";
        const strat = strat_opt orelse "B1.w1-autovec.w2-simple";
        layout_sel = layout;
        strat_sel = strat;
        name = b.fmt("{s}.{s}", .{ layout, strat });
        label = stratLabel(layout, strat) orelse {
            // Collect the valid strategy names for the error message.
            var valid = std.ArrayList(u8).initCapacity(b.allocator, 128) catch unreachable;
            for (strat_labels) |s| {
                if (std.mem.eql(u8, s.layout, layout)) {
                    valid.appendSlice(b.allocator, s.strat) catch unreachable;
                    valid.appendSlice(b.allocator, ", ") catch unreachable;
                }
            }
            if (valid.items.len == 0)
                std.debug.panic("unknown layout '{s}' (no strategies registered; see strat_labels in build.zig)", .{layout});
            std.debug.panic("invalid -Dstrat='{s}' for layout {s} — valid: {s}", .{ strat, layout, valid.items[0 .. valid.items.len - 2] });
        };
    }

    const opts = b.addOptions();
    opts.addOption([]const u8, "name", name);
    opts.addOption([]const u8, "label", label);
    // The golden files are generated by the reference sim only:
    // L1.B1.w1-autovec.w2-simple
    // (= arc stage 1's step, scavenged). The arc itself is no longer a build
    // target (relocated to .scratch/orig/).
    opts.addOption(bool, "is_reference", std.mem.eql(u8, name, "L1.B1.w1-autovec.w2-simple"));
    opts.addOption(f64, "death", death_q);
    opts.addOption(Mode, "mode", mode_enum);

    // --- raylib C library (compiled directly; raylib-zig build is broken on 0.17-dev) ---
    const raylib_lib = addRaylib(b, target, optimize);

    // --- main exe ---
    const exe = b.addExecutable(.{
        .name = "dod-particles",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    // --- Halide path: ONLY for cells whose walk 1 is halide (the w1-halide
    // walk). Fully gated: Zig strategies never touch python/Halide. The
    // generator (Python bindings) emits out/halide/<base>[_<variant>].{h,a}
    // with the runtime bundled; the exe links the static .a. No libHalide at
    // runtime.
    if (strat_sel) |strat| {
        if (halideGenBase(strat)) |base| {
            const layout = layout_sel.?;
            // If this python is missing, the generator step fails loudly at
            // build time; set HALIDE_PYTHON or create the env:
            //   uv sync --extra halide
            const python = b.graph.environ_map.get("HALIDE_PYTHON") orelse ".venv/bin/python";
            // Derive the Halide schedule from the strat name: a strat containing
            // "-par" gets {"parallel":true}; the plain strat gets the default.
            // (-Dhalide_variant still works for ad-hoc sweep variants; it adds
            // a suffix to the stem and is expected to be pre-generated.)
            const sched_json: []const u8 = if (std.mem.indexOf(u8, strat, "-par") != null)
                "{\"parallel\":true}"
            else
                "{}";
            // The stem: the base name, plus an optional explicit variant suffix.
            // For a "-par" strat we bake "_par" into the stem so the parallel .a
            // doesn't collide with the scalar .a (same generator, different schedule).
            const stem_par = if (std.mem.indexOf(u8, strat, "-par") != null) "_par" else "";
            const stem = if (halide_variant_opt) |v| b.fmt("{s}_{s}", .{ base, v }) else b.fmt("{s}{s}", .{ base, stem_par });
            const out_prefix = b.fmt("out/halide/{s}", .{stem});
            // Always run the generator for the derived schedule (no more
            // "pre-generated variant" expectation). A sweep can override the
            // schedule via -Dhalide_variant=<suffix> (pre-generated) if needed.
            const gen_dir = b.fmt("src/layouts/{s}/{s}_gen.py", .{ layoutDir(layout), base });
            const gen = b.addSystemCommand(&.{
                python,
                gen_dir,
                out_prefix,
                sched_json,
                b.fmt("{d}", .{death_q}), // generators that need q read argv[3] as a float
            });
            exe.step.dependOn(&gen.step);
            exe.root_module.addObjectFile(b.path(b.fmt("{s}.a", .{out_prefix})));
        }
    }

    exe.root_module.addOptions("options", opts);
    exe.root_module.addImport("raylib", raylib_module: {
        const rl_mod = b.createModule(.{
            .root_source_file = b.path("src/bindings/raylib.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        });
        rl_mod.linkLibrary(raylib_lib);
        break :raylib_module rl_mod;
    });

    b.installArtifact(exe);

    const run = b.addRunArtifact(exe);
    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run.step);

    // --- unit tests (render_opt's rasterizer byte-equivalence proof) ---
    const unit_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/test_root.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    unit_tests.root_module.addOptions("options", opts); // config.zig imports options (death pattern)
    const run_tests = b.addRunArtifact(unit_tests);
    const test_step = b.step("test", "Run unit tests (render_opt rasterizer equivalence)");
    test_step.dependOn(&run_tests.step);

    // --- manifest regeneration (optimization-framework §14/§17.4) ---
    // The declaration blocks in strategy files are the single source of truth;
    // experiments/cells/<layout>.md is a parser-generated artifact. This step
    // builds the exe in manifest mode and runs it, writing the manifest to
    // experiments/cells/L1.md. Check in the output; regenerate after editing
    // any cell_decl.
    const manifest_exe = b.addExecutable(.{
        .name = "dod-manifest",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    // Manifest mode: build with -Dmode=manifest and a default sim
    // (L1.B1.w1-autovec.w2-simple);
    // main.zig iterates the whole sim_map regardless of the selected sim.
    const manifest_opts = b.addOptions();
    manifest_opts.addOption([]const u8, "name", "L1.B1.w1-autovec.w2-simple");
    manifest_opts.addOption([]const u8, "label", "manifest");
    manifest_opts.addOption(bool, "is_reference", false);
    manifest_opts.addOption(f64, "death", 0.0);
    manifest_opts.addOption(Mode, "mode", .manifest);
    manifest_exe.root_module.addOptions("options", manifest_opts);
    manifest_exe.root_module.addImport("raylib", raylib_module: {
        const rl_mod = b.createModule(.{
            .root_source_file = b.path("src/bindings/raylib.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        });
        // raylib is linked so main.zig compiles (it imports the binding), but
        // manifest mode never touches it — no window, no rendering.
        rl_mod.linkLibrary(raylib_lib);
        break :raylib_module rl_mod;
    });
    const run_manifest = b.addRunArtifact(manifest_exe);
    const manifest_step = b.step("manifests", "Regenerate experiments/cells/L1.md from cell declarations");
    manifest_step.dependOn(&run_manifest.step);
}

pub const Mode = enum { play, bench, audit, manifest };

const StratEntry = struct { layout: []const u8, strat: []const u8, label: []const u8 };

/// The strategy registry (layout-verticals.md §9): every buildable
/// (layout, strat) and its HUD label. main.zig's comptime map must have an
/// arm for each. Layouts land one vertical at a time.
const strat_labels = [_]StratEntry{
    .{ .layout = "L1", .strat = "B1.w1-autovec.w2-simple", .label = "L1.B1.w1-autovec.w2-simple (B1: autovec branchy step + r0 render; reference sim)" },
    .{ .layout = "L1", .strat = "B1.w1-autovec.w2-opt", .label = "L1.B1.w1-autovec.w2-opt (B1: autovec branchy step + optimized r1 render)" },
    .{ .layout = "L1", .strat = "B1.w1-scalar.w2-simple", .label = "L1.B1.w1-scalar.w2-simple (B1: scalar-forced step + r0 render; de-vec control)" },
    .{ .layout = "L1", .strat = "B1.w1-autovec-par.w2-simple", .label = "L1.B1.w1-autovec-par.w2-simple (B1: parallel branchy math+decide | serial respawn | r0 render)" },
    .{ .layout = "L1", .strat = "B1.w1-blend.w2-simple", .label = "L1.B1.w1-blend.w2-simple (B1: Zig branchless blend + r0 render; STATISTICAL)" },
    .{ .layout = "L1", .strat = "B1.w1-blend-par.w2-simple", .label = "L1.B1.w1-blend-par.w2-simple (B1: parallel Zig blend + r0 render; STATISTICAL)" },
    .{ .layout = "L1", .strat = "B1.w1-halide.w2-simple", .label = "L1.B1.w1-halide.w2-simple (B1: Halide branchless blend + r0 render; STATISTICAL)" },
    .{ .layout = "L1", .strat = "B1.w1-halide.w2-opt", .label = "L1.B1.w1-halide.w2-opt (B1: Halide branchless blend + optimized r1 render; STATISTICAL)" },
    .{ .layout = "L1", .strat = "B1.w1-halide-par.w2-simple", .label = "L1.B1.w1-halide-par.w2-simple (B1: parallel Halide blend + r0 render; STATISTICAL; PREDICTED DRAM CHAMPION)" },
    .{ .layout = "L1", .strat = "B2.w1-autovec.w2-simple", .label = "L1.B2.w1-autovec.w2-simple (B2: math | decide+respawn | r0 render)" },
    .{ .layout = "L1", .strat = "B2.w1-autovec-par.w2-simple", .label = "L1.B2.w1-autovec-par.w2-simple (B2: parallel math | decide+respawn | r0 render)" },
    .{ .layout = "L1", .strat = "B2.w1-halide.w2-simple", .label = "L1.B2.w1-halide.w2-simple (B2: Halide math | decide+respawn | r0 render)" },
    .{ .layout = "L1", .strat = "B2.w1-halide-par.w2-simple", .label = "L1.B2.w1-halide-par.w2-simple (B2: parallel Halide math | decide+respawn | r0 render)" },
    .{ .layout = "L1", .strat = "B3.w1-halide.w2-simple", .label = "L1.B3.w1-halide.w2-simple (B3: Halide math+decide→mask | scan+respawn | r0 render)" },
    .{ .layout = "L1", .strat = "B3.w1-autovec.w2-simple", .label = "L1.B3.w1-autovec.w2-simple (B3: math+decide→mask | scan+respawn | r0 render)" },
    .{ .layout = "L1", .strat = "B3.w1-autovec-par.w2-rmerge", .label = "L1.B3.w1-autovec-par.w2-rmerge (B3: parallel math+decide→mask | serial respawn | r0 render; DE-RISK)" },
    .{ .layout = "L1", .strat = "B4.w1-autovec.w2-simple", .label = "L1.B4.w1-autovec.w2-simple (B4: math+decide→list | respawn-dead | r0 render)" },
    .{ .layout = "L1", .strat = "B4.w1-autovec-par.w2-rmerge", .label = "L1.B4.w1-autovec-par.w2-rmerge (B4: parallel math+decide→list | ranked-merge respawn | r0 render)" },
    .{ .layout = "L1", .strat = "B5.w1-fused", .label = "L1.B5.w1-fused (B5: fused math+decide+respawn+render; FRAMEBUFFER-ONLY)" },
    .{ .layout = "L1", .strat = "B6.w1-autovec.w2-fused", .label = "L1.B6.w1-autovec.w2-fused (B6: math | fused decide+respawn+render; FRAMEBUFFER-ONLY)" },
    .{ .layout = "L1", .strat = "B7.w1-autovec.w2-fused", .label = "L1.B7.w1-autovec.w2-fused (B7: math+decide→mask | fused scan+respawn+render; FRAMEBUFFER-ONLY)" },
    .{ .layout = "L1", .strat = "B8.w1-autovec.w2-fused", .label = "L1.B8.w1-autovec.w2-fused (B8: math+decide→list | fused respawn+render(dead) | render(live); FRAMEBUFFER-ONLY)" },
};

/// Returns the generator base name for a Halide cell, or null if the cell
/// is not Halide. Used both to gate the generator step and to find the .a.
/// Any cell containing "w1-halide" maps to "w1-halide" (the walk-1 Halide
/// pipeline generator, in walks/).
fn halideGenBase(strat: []const u8) ?[]const u8 {
    if (std.mem.indexOf(u8, strat, "w1-halide") != null) {
        // Map the cell's blueprint prefix: B1.w1-halide / B2.w1-halide / B3.w1-halide.
        // Each has its own generator + FFI binding at the layout root.
        if (std.mem.startsWith(u8, strat, "B2.")) return "B2.w1-halide";
        if (std.mem.startsWith(u8, strat, "B3.")) return "B3.w1-halide";
        return "B1.w1-halide";
    }
    return null;
}

/// Layout id -> folder name (one per vertical; extended as verticals land).
fn layoutDir(layout: []const u8) []const u8 {
    const map = std.StaticStringMap([]const u8).initComptime(.{
        .{ "L1", "L1_aos_full" },
    });
    return map.get(layout) orelse
        std.debug.panic("unknown layout '{s}' (see layoutDir in build.zig)", .{layout});
}

fn stratLabel(layout: []const u8, strat: []const u8) ?[]const u8 {
    for (strat_labels) |s|
        if (std.mem.eql(u8, s.layout, layout) and std.mem.eql(u8, s.strat, strat)) return s.label;
    return null;
}

fn addRaylib(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) *std.Build.Step.Compile {
    const c_flags = &.{
        "-std=c11",
        "-DPLATFORM_DESKTOP",
        "-DGRAPHICS_API_OPENGL_33",
        // Disable raylib's image-export helpers (ExportImage* — unused by us;
        // --record pipes raw RGBA straight into ffmpeg, no image lib). Keeps
        // raylib lean and avoids bundling stb_image_write inside rtextures.c.
        "-DSUPPORT_IMAGE_EXPORT=0",
        "-ObjC",
    };

    const sources = [_][]const u8{
        "rcore.c",
        "rglfw.c",
        "rshapes.c",
        "rtextures.c",
        "rtext.c",
        "rmodels.c",
    };

    const lib = b.addLibrary(.{
        .name = "raylib",
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
        .linkage = .static,
    });
    inline for (sources) |s| {
        lib.root_module.addCSourceFile(.{
            .file = b.path("vendor/raylib/src/" ++ s),
            .flags = c_flags,
        });
    }
    lib.root_module.addIncludePath(b.path("vendor/raylib/src"));
    lib.root_module.addIncludePath(b.path("vendor/raylib/src/external/glfw/include"));

    lib.root_module.linkFramework("Cocoa", .{});
    lib.root_module.linkFramework("IOKit", .{});
    lib.root_module.linkFramework("CoreVideo", .{});
    lib.root_module.linkFramework("CoreFoundation", .{});
    lib.root_module.linkFramework("OpenGL", .{});

    b.installArtifact(lib);
    return lib;
}
