// The manifest formatter (optimization-framework.md §14/§17.4).
//
// The declaration blocks in strategy files are the single source of truth;
// `zig build manifests` prints this formatted roster to stdout as a
// diagnostic of what's registered in sim_map (reporting-and-analysis.md
// §9.5: there is no checked-in manifest file). This module formats every
// registered cell's CellDecl into the §8-style declaration block.
//
// A cell whose H doesn't declare `cell_decl` yet (not relabeled) is listed
// as `pending` — the manifest reflects the honest state of the rollout.

const std = @import("std");
const fw = @import("sim.zig");

/// A registered cell name + its Sim type (from main.zig's sim_map).
pub fn Entry(comptime Sim: type) type {
    return struct {
        name: []const u8,
        sim: type,
        _cd: ?fw.CellDecl = Sim.cell_decl,
    };
}

/// Print the full manifest from a comptime StaticStringMap(type) (sim_map)
/// to the given writer. main.zig wires this to stdout (`zig build manifests`).
pub fn print(comptime map: anytype, w: anytype) !void {
    try w.print("# Cell manifest — L1\n\n", .{});
    try w.print("<!-- AUTO-GENERATED by `zig build manifests`. Do not edit. -->\n", .{});
    try w.print("<!-- Source of truth: the cell_decl in each strategy file (§8). -->\n\n", .{});
    try w.print("Cells whose declaration is `pending` have not yet been relabeled into\n", .{});
    try w.print("the new vocabulary (Phase 0 rollout in progress).\n\n", .{});

    // map is a comptime StaticStringMap(type); types are comptime-only, so
    // we iterate the kvs directly with inline for (no runtime for over types).
    const kvs = map.kvs.*;
    inline for (0..kvs.len) |i| {
        const name = kvs.keys[i];
        const Sim: type = kvs.values[i];
        if (Sim.cell_decl) |cd| {
            try printCell(name, cd, w);
        } else {
            try w.print("## {s}\n\n```\n(pending — not yet declared)\n```\n\n", .{name});
        }
    }
}

fn printCell(name: []const u8, cd: fw.CellDecl, w: anytype) !void {
    try w.print("## {s}\n\n```\n", .{name});
    try w.print("layout:        {s}\n", .{cd.layout});
    try w.print("blueprint:     {s}  ({s})\n", .{ @tagName(cd.blueprint), cd.blueprint.structure() });
    try w.print("ordering:      {s}\n", .{@tagName(cd.ordering)});
    try w.print("intermediates: {s}\n", .{@tagName(cd.intermediates)});
    for (cd.walks, 0..) |walk, i| {
        try w.print("walk{d}: {{ impl: {s}, schedule: {s}, parallel: {s}, variant: {s} }}\n", .{
            i + 1,
            @tagName(walk.impl),
            @tagName(walk.schedule),
            @tagName(walk.parallel),
            @tagName(walk.variant),
        });
    }
    try w.print("golden:        {s}\n", .{@tagName(cd.golden)});
    if (cd.halide_expressible.len > 0)
        try w.print("halide_expressible: {s}\n", .{cd.halide_expressible});
    try w.print("```\n\n", .{});
}

/// Print a single cell's declaration to stderr (for the bench run header).
/// Uses std.debug.print (always stderr) — every bench run shows its axes.
pub fn printCellHeader(name: []const u8, cd: fw.CellDecl) void {
    std.debug.print("=== Cell ===\n", .{});
    std.debug.print("  name:          {s}\n", .{name});
    std.debug.print("  layout:        {s}\n", .{cd.layout});
    std.debug.print("  blueprint:     {s} ({s})\n", .{ @tagName(cd.blueprint), cd.blueprint.structure() });
    std.debug.print("  ordering:      {s}\n", .{@tagName(cd.ordering)});
    std.debug.print("  intermediates: {s}\n", .{@tagName(cd.intermediates)});
    for (cd.walks, 0..) |walk, i| {
        std.debug.print("  walk{d}:         {{ impl: {s}, schedule: {s}, parallel: {s}, variant: {s} }}\n", .{
            i + 1,
            @tagName(walk.impl),
            @tagName(walk.schedule),
            @tagName(walk.parallel),
            @tagName(walk.variant),
        });
    }
    std.debug.print("  golden:        {s}\n", .{@tagName(cd.golden)});
    if (cd.halide_expressible.len > 0)
        std.debug.print("  halide_expr:   {s}\n", .{cd.halide_expressible});
    std.debug.print("\n", .{});
}
