// The Sim interface contract.
//
// No vtable: the driver is generic over a concrete Sim type chosen at compile
// time. Each stage's sim.zig exposes a `pub const Sim = struct { ... }` with
// these methods. (Stage 5 teaches that per-particle vtables are bad; we must
// not use one ourselves at the per-frame boundary either — generics let us
// skip the question entirely.)

const std = @import("std");
const vec = @import("vec.zig");

pub const Vec3 = vec.Vec3;
pub const Vec4 = vec.Vec4;

pub const ParticleKind = enum(u8) { smoke, spark, debris };

/// Golden class (layout-matrix.md §8.2): how the cell relates to the
/// golden files. Default (no declaration) = bit_exact trajectory equality.
/// `.statistical` = the cell intentionally uses a different RNG model
/// (per-particle hash respawn, halide-doc §2.3 B1): trajectories diverge
/// from stage1.bin by design; correctness is distributional. The bench
/// skips the golden compare loudly, never silently.
pub const GoldenClass = enum { bit_exact, statistical };

/// Render-color semantics (layout-matrix.md §2.3): the frame golden is
/// generated by the reference cell, whose color is always
/// kindColor(current kind). A cell declares `.stale_cold` when its stored
/// color is write-once (respawn re-olls kind but not color — an
/// arc-documented cosmetic optimization that skips the cold write to avoid
/// an RFO miss). The sim golden can't see the difference (pos/vel only);
/// the frame golden can — so `.stale_cold` cells skip it, loudly, with the
/// reason printed. Cells that don't declare default to `.current_kind`.
pub const RenderColorSemantics = enum { current_kind, stale_cold };

// =========================================================================
// The cell declaration (optimization-framework.md §8).
//
// A cell is a named strategy file whose header is a DECLARATION BLOCK: the
// full axis assignment (layout × blueprint × ordering × intermediates ×
// per-walk attrs × golden × halide-expressibility). This makes every axis
// explicit and every comparison's differences enumerable from the
// declarations — the honest version of "vary one axis."
//
// IMPORTANT: CellDecl is a DECLARATION (metadata), not an execution engine.
// It does not implement walks or chain their outputs to inputs. The strategy
// code (H.step / H.render) still implements the walks and their data flow;
// CellDecl describes that data flow for attribution, manifest generation,
// and runtime printing. The intermediates field names what carries the death
// decision between walks (none/mask/list) — the strategy code owns the actual
// scratch allocation and the read/write discipline.
//
// Blueprint defines the walk STRUCTURE (which logical stages fuse into which
// walk). The walks array's length must match the blueprint's walk count
// (checked at comptime). Each WalkDecl carries that walk's impl, schedule,
// parallel scheme, and semantic variant.
// =========================================================================

/// The eight blueprints (optimization-framework.md §3). Generated by a rule:
/// Decide rides with Integrate or Respawn; choose an intermediate
/// ∈ {none, mask, list}; choose a contiguous fusion of
/// {Integrate+Decide, Respawn, Render} into walks.
pub const Blueprint = enum {
    B1, // math+decide+respawn | render                          (none)
    B2, // math | decide+respawn | render                        (none)
    B3, // math+decide→mask | mask-scan+respawn | render         (mask)
    B4, // math+decide→list | respawn-dead-only | render         (list)
    B5, // math+decide+respawn+render                            (none)
    B6, // math | decide+respawn+render                          (none)
    B7, // math+decide→mask | mask-scan+respawn+render           (mask)
    B8, // math+decide→list | respawn+render(dead) | render(live)(list+mask)

    /// Human-readable walk structure for this blueprint (for printing).
    pub fn structure(self: Blueprint) []const u8 {
        return switch (self) {
            .B1 => "math+decide+respawn | render",
            .B2 => "math | decide+respawn | render",
            .B3 => "math+decide→mask | mask-scan+respawn | render",
            .B4 => "math+decide→list | respawn-dead-only | render",
            .B5 => "math+decide+respawn+render",
            .B6 => "math | decide+respawn+render",
            .B7 => "math+decide→mask | mask-scan+respawn+render",
            .B8 => "math+decide→list | respawn+render(dead) | render(live)",
        };
    }

    /// How many walks this blueprint has (length of the walks array).
    pub fn nWalks(self: Blueprint) usize {
        return switch (self) {
            .B1 => 2, .B2 => 3, .B3 => 3, .B4 => 3,
            .B5 => 1, .B6 => 2, .B7 => 2, .B8 => 3,
        };
    }
};

/// Storage permutation policy (orthogonal to blueprint — the home of arc
/// stage 4 live-compaction, sortbykind, doublebuf).
pub const Ordering = enum { identity, kind_sorted, live_compacted, double_buffered };

/// What carries the death decision between walks.
pub const Intermediate = enum { none, mask, list, mask_and_list };

/// Per-walk: who computes it.
pub const WalkImpl = enum { zig, halide };

/// Per-walk: the density knobs (vector width, unroll, tile, splat variant).
pub const WalkSchedule = enum {
    scalar, // no vectorization (forced or natural)
    auto, // compiler auto-vectorizes (the default for unannotated Zig walks)
    vw2, vw4, vw8, // explicit vector widths
    unroll,
    tile,
    r0, // naive splat
    r1, // optimized splat (LUT, packed, tight loop)
};

/// Per-walk: the parallel scheme (closed vocabulary, §4).
pub const WalkParallel = enum {
    none,
    data_parallel, // parallel(i) over the particle dim
    ranked_merge, // parallel count → prefix sum → parallel respawn-by-rank
    branchless, // fully parallel, no merge (per-particle hash RNG)
    render_reduce, // per-thread framebuffers, reduce at end
};

/// Per-walk: the semantic variant (drives golden class, §6).
pub const WalkVariant = enum {
    none, // walk has no respawn/RNG semantics (e.g. render walk)
    branchy, // branchy respawn, ordered spawn RNG (B1-branchy)
    blend, // branchless blend respawn, per-particle hash RNG (B1-blend)
    ordered, // ordered spawn RNG, respawn via mask/list scan (B3/B4)
};

/// One walk's declared attributes.
pub const WalkDecl = struct {
    impl: WalkImpl,
    schedule: WalkSchedule = .scalar,
    parallel: WalkParallel = .none,
    variant: WalkVariant = .none,
};

/// The full cell declaration (the contract). Declared on the strategy's H
/// struct as `pub const cell_decl: fw.CellDecl = .{ ... };` and exposed via
/// Sim.cell_decl by the Strategy helper.
pub const CellDecl = struct {
    layout: []const u8,
    blueprint: Blueprint,
    ordering: Ordering = .identity,
    intermediates: Intermediate = .none,
    walks: []const WalkDecl,
    golden: GoldenClass = .bit_exact,
    /// Prose: "walk1 yes; walk2 no (reason); walk3 n/a" — cited, not structured.
    halide_expressible: []const u8 = "",

    /// Comptime check: the walks array length matches the blueprint.
    pub fn validate(self: CellDecl) void {
        if (self.walks.len != self.blueprint.nWalks())
            @compileError(std.fmt.comptimePrint("CellDecl: blueprint {s} requires {d} walks, got {d}", .{ @tagName(self.blueprint), self.blueprint.nWalks(), self.walks.len }));
    }
};

pub const Desc = struct {
    n: usize,
    seed: u64,
    // physics params are NOT here — they live in config.zig, shared, so every
    // stage's math is provably identical. Desc only describes population/seed.
    /// Worker count for .par cells (layout-matrix.md §2.7); serial cells
    /// ignore it. Default 1 = serial.
    threads: usize = 1,
};

/// One field's raw bytes across the whole particle array, for the data-density
/// audit (Acton's zip-test, §data-audit). `bytes` is the contiguous memory
/// of this field over all N particles in storage order — so the gzip ratio
/// is a lower-bound estimate of the field's information density.
/// - Low density  → field is redundant per-particle (constant / few distinct
///   values). Candidate to drop from the hot loop or stop storing per-element.
/// - High density → field carries real signal. Leave it alone.
///
/// The set of names + how bytes are sliced IS a fingerprint of the stage's
/// layout: stage 1 emits AoS-strided blobs; stage 3 emits per-component SoA
/// streams. Watching mean density rise across stages is the qualitative twin
/// of watching ns/particle fall.
pub const FieldDump = struct {
    name: []const u8,
    bytes: []u8,
};

// Each stage's Sim must expose:
//   pub const Sim = struct {
//       <stage-specific fields — the layout IS the lesson>
//       pub fn init(alloc: std.mem.Allocator, desc: Desc) anyerror!*@This();
//       pub fn step(self: *@This(), dt: f32) void;
//       pub fn render(self: *const @This(), fb: []u8, w: u32, h: u32) void;
//       pub fn deinit(self: *@This()) void;
//       pub fn snapshot(self: *const @This(), out: []f32) void;  // n*6 floats (px,py,pz,vx,vy,vz)
//       pub fn bytesPerParticle(self: *const @This()) usize;
//       pub fn dumpFields(self: *const @This(), alloc: std.mem.Allocator)
//           ![]FieldDump;  // raw bytes per field, for the density audit
//   };
//
// `dumpFields` is layout-aware: L1 strides an AoS array; L4 emits
// per-component SoA streams. The audit output therefore reflects the layout
// transformation itself.
//
// The HUD/bench label comes from the build options (`@import("options").label`,
// resolved in build.zig from -Dlayout/-Dstrat or the -Dstage alias).

/// The strategy harness (layout-verticals.md §4.4): generates the Sim
/// contract for a layout strategy — init/deinit owning a `Data`, the
/// framework-visible `n`, delegation of the storage-determined methods, and
/// the default render (`Data.renderR0`). A strategy file supplies only its
/// schedule hooks:
///
///   const Data = @import("data.zig").Data;
///   const H = struct {
///       pub fn step(sim: *Sim, dt: f32) void { ... }
///       (use `sim: anytype` if another strategy re-exports the step —
///       each fw.Strategy instantiation is a distinct type)
///       // optional overrides/decls:
///       // pub fn render(sim: *const Sim, fb: []u8, w: u32, h: u32) void
///       // pub const Extra = struct { ... }    — strategy-owned state
///       // pub fn initExtra(sim: *Sim) !void   — scratch allocation
///       // pub fn deinitExtra(sim: *Sim) void   — scratch free
///       // pub fn scratchBytes(sim: *const Sim) usize — reported in bytes/p
///       // pub const golden_class: fw.GoldenClass = .statistical;
///       // pub const render_color_semantics: fw.RenderColorSemantics = .stale_cold;
///   };
///   pub const Sim = fw.Strategy(Data, H);
///
/// Standard state every strategy gets: the `Data`, the spawn RNG (shared
/// stream: `Data.init` draws the initial spawns from it, `step` draws
/// respawns — same sequence as the arc's single-RNG sims, so the golden
/// holds), a DEDICATED kill RNG (drawn only under q>0 so spawn draws stay
/// comparable across rates, optimization-framework.md §7), and the frame
/// counter (used by the B1-blend per-particle hash RNG), and the thread count
/// (serial strategies ignore).
pub fn Strategy(comptime Data: type, comptime H: type) type {
    return struct {
        const Self = @This();

        pub const golden_class: GoldenClass = if (@hasDecl(H, "cell_decl")) H.cell_decl.golden else if (@hasDecl(H, "golden_class")) H.golden_class else .bit_exact;
        pub const render_color_semantics: RenderColorSemantics = if (@hasDecl(H, "render_color_semantics")) H.render_color_semantics else .current_kind;
        /// The cell declaration (§8). Optional during the Phase-0 rollout:
        /// cells without one report `cell_decl = null` (manifest marks them
        /// pending). Once all cells are relabeled, this becomes required.
        pub const cell_decl: ?CellDecl = if (@hasDecl(H, "cell_decl")) blk: {
            const cd = H.cell_decl;
            cd.validate();
            break :blk cd;
        } else null;

        pub const Extra = if (@hasDecl(H, "Extra")) H.Extra else void;

        alloc: std.mem.Allocator,
        data: Data,
        extra: Extra = undefined, // strategy-owned (scratch, pool, ...)
        rng: std.Random.DefaultPrng,
        kill_rng: std.Random.DefaultPrng, // dedicated kill stream (drawn only when q>0, §7)
        frame: usize, // step counter (B1-blend per-particle hash RNG uses this)
        threads: usize,
        n: usize, // mirrors data.n — framework drivers read sim.n directly

        pub fn init(alloc: std.mem.Allocator, desc: Desc) anyerror!*Self {
            const self = try alloc.create(Self);
            errdefer alloc.destroy(self);
            self.alloc = alloc;
            self.rng = std.Random.DefaultPrng.init(desc.seed);
            self.kill_rng = std.Random.DefaultPrng.init(desc.seed ^ 0xDEAD_BEEF);
            self.frame = 0;
            self.threads = desc.threads;
            self.n = desc.n;
            // Data.init draws the initial spawns from self.rng (shared-stream
            // discipline: identical sequence to the arc's single-RNG sims).
            self.data = try Data.init(alloc, &self.rng, desc);
            errdefer self.data.deinit(alloc);
            if (@hasDecl(H, "initExtra")) try H.initExtra(self, desc);
            return self;
        }

        /// step takes an optional framebuffer so fused blueprints (B5/B6/B7)
        /// can splat inside the step walk (§17.7). fb == null = step-only
        /// mode (no splat; the step bench and golden capture use this).
        /// Unfused cells (B1-B4) ignore fb.
        pub fn step(self: *Self, dt: f32, fb: ?[]u8, w: u32, h: u32) void {
            H.step(self, dt, fb, w, h);
            self.frame +%= 1; // B1-blend hash RNG frame counter (free otherwise)
        }

        pub fn render(self: *const Self, fb: []u8, w: u32, h: u32) void {
            if (@hasDecl(H, "render")) {
                H.render(self, fb, w, h);
            } else {
                self.data.renderR0(fb, w, h);
            }
        }

        pub fn deinit(self: *Self) void {
            if (@hasDecl(H, "deinitExtra")) H.deinitExtra(self);
            self.data.deinit(self.alloc);
            self.alloc.destroy(self);
        }

        pub fn snapshot(self: *const Self, out: []f32) void {
            self.data.snapshot(out);
        }

        pub fn bytesPerParticle(self: *const Self) usize {
            const scratch: usize = if (@hasDecl(H, "scratchBytes")) H.scratchBytes(self) else 0;
            return self.data.bytesPerParticle() + scratch;
        }

        pub fn dumpFields(self: *const Self, alloc: std.mem.Allocator) ![]FieldDump {
            return self.data.dumpFields(alloc);
        }
    };
}
