// The Sim interface contract.
//
// No vtable: the driver is generic over a concrete Sim type chosen at compile
// time. Each stage's sim.zig exposes a `pub const Sim = struct { ... }` with
// these methods. (Stage 5 teaches that per-particle vtables are bad; we must
// not use one ourselves at the per-frame boundary either — generics let us
// skip the question entirely.)

const std = @import("std");
const vec = @import("vec.zig");

pub const Vec3 = vec.Vec3;
pub const Vec4 = vec.Vec4;

pub const ParticleKind = enum(u8) { smoke, spark, debris };

/// Golden class (mem-layout-matrix.md §8.2): how the algorithm relates to the
/// golden files. Default (no declaration) = bit_exact trajectory equality.
/// `.statistical` = the algorithm intentionally uses a different RNG model
/// (per-particle hash respawn, halide-doc §2.3 AF01): trajectories diverge
/// from stage1.bin by design; correctness is distributional. The bench
/// skips the golden compare loudly, never silently.
pub const GoldenClass = enum { bit_exact, statistical, framebuffer_only };

/// Render-color semantics (mem-layout-matrix.md §2.3): the frame golden is
/// generated by the reference algorithm, whose color is always
/// kindColor(current kind). An algorithm declares `.stale_cold` when its stored
/// color is write-once (respawn re-rolls kind but not color — an
/// arc-documented cosmetic optimization that skips the cold write to avoid
/// an RFO miss). The sim golden can't see the difference (pos/vel only);
/// the frame golden can — so `.stale_cold` algorithms skip it, loudly, with the
/// reason printed. Algorithms that don't declare default to `.current_kind`.
pub const RenderColorSemantics = enum { current_kind, stale_cold };

// =========================================================================
// The algorithm meta (optimization-framework.md §8).
//
// An algorithm is a named file whose header is a META BLOCK: the
// full axis assignment (mem_layout × algo_fam × ordering × intermediates ×
// per-loop attrs × golden × halide-expressibility). This makes every axis
// explicit and every comparison's differences enumerable from the
// declarations — the honest version of "vary one axis."
//
// IMPORTANT: AlgorithmMeta is a DECLARATION (metadata), not an execution engine.
// It does not implement loops or chain their outputs to inputs. The algorithm
// code (H.step) still implements the loops and their data flow;
// AlgorithmMeta describes that data flow for attribution, manifest generation,
// and runtime printing. The intermediates field names what carries the death
// decision between loops (none/mask/list) — the algorithm code owns the actual
// scratch allocation and the read/write discipline.
//
// AlgorithmFamily defines the loop STRUCTURE (which logical stages fuse into
// which loop). The loops array's length must match the family's loop count
// (checked at comptime). Each LoopMeta carries that loop's impl, schedule,
// parallel scheme, and semantic variant.
// =========================================================================

/// The eight algorithm families (optimization-framework.md §3). Generated by a rule:
/// Decide rides with Integrate or Respawn; choose an intermediate
/// ∈ {none, mask, list}; choose a contiguous fusion of
/// {Integrate+Decide, Respawn, Render} into loops.
pub const AlgorithmFamily = enum {
    AF01, // math+decide+respawn | render                          (none)
    AF02, // math | decide+respawn | render                        (none)
    AF03, // math+decide→mask | mask-scan+respawn | render         (mask)
    AF04, // math+decide→list | respawn-dead-only | render         (list)
    AF05, // math+decide+respawn+render                            (none)
    AF06, // math | decide+respawn+render                          (none)
    AF07, // math+decide→mask | mask-scan+respawn+render           (mask)
    AF08, // math+decide→list | respawn+render(dead) | render(live)(list+mask)

    /// Human-readable loop structure for this family (for printing).
    pub fn structure(self: AlgorithmFamily) []const u8 {
        return switch (self) {
            .AF01 => "math+decide+respawn | render",
            .AF02 => "math | decide+respawn | render",
            .AF03 => "math+decide→mask | mask-scan+respawn | render",
            .AF04 => "math+decide→list | respawn-dead-only | render",
            .AF05 => "math+decide+respawn+render",
            .AF06 => "math | decide+respawn+render",
            .AF07 => "math+decide→mask | mask-scan+respawn+render",
            .AF08 => "math+decide→list | respawn+render(dead) | render(live)",
        };
    }

    /// How many loops this family has (length of the loops array).
    pub fn nLoops(self: AlgorithmFamily) usize {
        return switch (self) {
            .AF01 => 2, .AF02 => 3, .AF03 => 3, .AF04 => 3,
            .AF05 => 1, .AF06 => 2, .AF07 => 2, .AF08 => 3,
        };
    }
};

/// Storage permutation policy (orthogonal to family — the home of arc
/// stage 4 live-compaction, sortbykind, doublebuf).
pub const Ordering = enum { identity, kind_sorted, live_compacted, double_buffered };

/// What carries the death decision between loops.
pub const Intermediate = enum { none, mask, list, mask_and_list };

/// Per-loop: who computes it.
pub const LoopImpl = enum { zig, halide };

/// Per-loop: the density knobs (vector width, unroll, tile, splat variant).
pub const LoopSchedule = enum {
    scalar, // no vectorization (forced or natural)
    auto, // compiler auto-vectorizes (the default for unannotated Zig loops)
    vw2, vw4, vw8, // explicit vector widths
    unroll,
    tile,
    r0, // naive splat
    r1, // optimized splat (LUT, packed, tight loop)
    fused, // splat inlined into the physics loop (AF05–AF08, §17.7)
};

/// Per-loop: the parallel scheme (closed vocabulary, §4).
pub const LoopParallel = enum {
    none,
    data_parallel, // parallel(i) over the particle dim
    ranked_merge, // parallel count → prefix sum → parallel respawn-by-rank
    branchless, // fully parallel, no merge (per-particle hash RNG)
    render_reduce, // per-thread framebuffers, reduce at end
};

/// Per-loop: the semantic variant (drives golden class, §6).
pub const LoopVariant = enum {
    none, // loop has no respawn/RNG semantics (e.g. render loop)
    branchy, // branchy respawn, ordered spawn RNG (AF01-branchy)
    blend, // branchless blend respawn, per-particle hash RNG (AF01-blend)
    ordered, // ordered spawn RNG, respawn via mask/list scan (AF03/AF04)
};

/// One loop's declared attributes.
pub const LoopMeta = struct {
    impl: LoopImpl,
    schedule: LoopSchedule = .scalar,
    parallel: LoopParallel = .none,
    variant: LoopVariant = .none,
};

/// The full algorithm meta (the contract). Declared on the strategy's H
/// struct as `pub const algo_meta: fw.AlgorithmMeta = .{ ... };` and exposed via
/// Sim.algo_meta by the Strategy helper.
pub const AlgorithmMeta = struct {
    mem_layout: []const u8,
    algo_fam: AlgorithmFamily,
    ordering: Ordering = .identity,
    intermediates: Intermediate = .none,
    loops: []const LoopMeta,
    golden: GoldenClass = .bit_exact,
    /// Prose: "loop1 yes; loop2 no (reason); loop3 n/a" — cited, not structured.
    halide_expressible: []const u8 = "",

    /// Comptime check: the loops array length matches the family.
    pub fn validate(self: AlgorithmMeta) void {
        if (self.loops.len != self.algo_fam.nLoops())
            @compileError(std.fmt.comptimePrint("AlgorithmMeta: algo_fam {s} requires {d} loops, got {d}", .{ @tagName(self.algo_fam), self.algo_fam.nLoops(), self.loops.len }));
    }
};

pub const Desc = struct {
    n: usize,
    seed: u64,
    // physics params are NOT here — they live in config.zig, shared, so every
    // stage's math is provably identical. Desc only describes population/seed.
    /// Worker count for .par algorithms (mem-layout-matrix.md §2.7); serial
    /// algorithms ignore it. Default 1 = serial.
    threads: usize = 1,
};

/// One field's raw bytes across the whole particle array, for the data-density
/// audit (Acton's zip-test, §data-audit). `bytes` is the contiguous memory
/// of this field over all N particles in storage order — so the gzip ratio
/// is a lower-bound estimate of the field's information density.
/// - Low density  → field is redundant per-particle (constant / few distinct
///   values). Candidate to drop from the hot loop or stop storing per-element.
/// - High density → field carries real signal. Leave it alone.
///
/// The set of names + how bytes are sliced IS a fingerprint of the stage's
/// mem_layout: stage 1 emits AoS-strided blobs; stage 3 emits per-component SoA
/// streams. Watching mean density rise across stages is the qualitative twin
/// of watching ns/particle fall.
pub const FieldDump = struct {
    name: []const u8,
    bytes: []u8,
};

// Each algorithm's Sim must expose (the Strategy helper generates all but `H.step`):
//   pub const Sim = struct {
//       <framework-owned fields: data, rng, kill_rng, frame, threads, n>
//       pub fn init(alloc: std.mem.Allocator, desc: Desc) anyerror!*@This();
//       pub fn step(self: *@This(), dt: f32, fb: []u8, w: u32, h: u32) void;  // math + splat, always
//       pub fn deinit(self: *@This()) void;
//       pub fn snapshot(self: *const @This(), out: []f32) void;  // n*6 floats (px,py,pz,vx,vy,vz)
//       pub fn bytesPerParticle(self: *const @This()) usize;
//       pub fn dumpFields(self: *const @This(), alloc: std.mem.Allocator)
//           ![]FieldDump;  // raw bytes per field, for the density audit
//   };
//
// `dumpFields` is mem_layout-aware: ML01 strides an AoS array; ML04 emits
// per-component SoA streams. The audit output therefore reflects the mem_layout
// transformation itself.
//
// The bench label comes from the build options (`@import("options").label`,
// resolved in build.zig from -Dmem_layout/-Dalgo).

/// The strategy harness (mem-layout-verticals.md §4.4): generates the Sim
/// contract for a mem_layout strategy — init/deinit owning a `Data`, the
/// framework-visible `n`, and delegation of the storage-determined methods.
/// A strategy file supplies only its `step` (math + splat, always):
///
///   const Data = @import("data.zig").Data;
///   const H = struct {
///       pub fn step(sim: *Sim, dt: f32, fb: []u8, w: u32, h: u32) void { ... }
///       (use `sim: anytype` so any algorithm can share physics helpers)
///       // optional overrides/decls:
///       // pub const Extra = struct { ... }    — strategy-owned state
///       // pub fn initExtra(sim: *Sim) !void   — scratch allocation
///       // pub fn deinitExtra(sim: *Sim) void   — scratch free
///       // pub fn scratchBytes(sim: *const Sim) usize — reported in bytes/p
///       // pub const golden_class: fw.GoldenClass = .statistical;
///       // pub const render_color_semantics: fw.RenderColorSemantics = .stale_cold;
///   };
///   pub const Sim = fw.Strategy(Data, H);
///
/// Standard state every strategy gets: the `Data`, the spawn RNG (shared
/// stream: `Data.init` draws the initial spawns from it, `step` draws
/// respawns — same sequence as the arc's single-RNG sims, so the golden
/// holds), a DEDICATED kill RNG (drawn only under q>0 so spawn draws stay
/// comparable across rates, optimization-framework.md §7), and the frame
/// counter (used by the AF01-blend per-particle hash RNG), and the thread count
/// (serial strategies ignore).
pub fn Strategy(comptime Data: type, comptime H: type) type {
    return struct {
        const Self = @This();

        pub const golden_class: GoldenClass = if (@hasDecl(H, "algo_meta")) H.algo_meta.golden else if (@hasDecl(H, "golden_class")) H.golden_class else .bit_exact;
        pub const render_color_semantics: RenderColorSemantics = if (@hasDecl(H, "render_color_semantics")) H.render_color_semantics else .current_kind;
        /// The algorithm meta (§8). Optional during the Phase-0 rollout:
        /// algorithms without one report `algo_meta = null` (manifest marks them
        /// pending). Once all algorithms are relabeled, this becomes required.
        pub const algo_meta: ?AlgorithmMeta = if (@hasDecl(H, "algo_meta")) blk: {
            const cd = H.algo_meta;
            cd.validate();
            break :blk cd;
        } else null;

        pub const Extra = if (@hasDecl(H, "Extra")) H.Extra else void;

        alloc: std.mem.Allocator,
        data: Data,
        extra: Extra = undefined, // strategy-owned (scratch, pool, ...)
        rng: std.Random.DefaultPrng,
        kill_rng: std.Random.DefaultPrng, // dedicated kill stream (drawn only when q>0, §7)
        frame: usize, // step counter (AF01-blend per-particle hash RNG uses this)
        threads: usize,
        n: usize, // mirrors data.n — framework drivers read sim.n directly

        pub fn init(alloc: std.mem.Allocator, desc: Desc) anyerror!*Self {
            const self = try alloc.create(Self);
            errdefer alloc.destroy(self);
            self.alloc = alloc;
            self.rng = std.Random.DefaultPrng.init(desc.seed);
            self.kill_rng = std.Random.DefaultPrng.init(desc.seed ^ 0xDEAD_BEEF);
            self.frame = 0;
            self.threads = desc.threads;
            self.n = desc.n;
            // Data.init draws the initial spawns from self.rng (shared-stream
            // discipline: identical sequence to the arc's single-RNG sims).
            self.data = try Data.init(alloc, &self.rng, desc);
            errdefer self.data.deinit(alloc);
            if (@hasDecl(H, "initExtra")) try H.initExtra(self, desc);
            return self;
        }

        /// step takes an optional framebuffer so fused families (AF05/AF06/AF07)
        /// can splat inside the step loop (§17.7). fb == null = step-only
        /// One call: math + decide + respawn + splat, always (§17.7 as revised).
        /// The splat always runs — the driver always provides a real fb. The
        /// clear is NOT here (the driver owns it: play memsets each frame, bench
        /// memsets once before the timed loop). Unfused families (AF01–AF04) put
        /// the splat in a separate pass after physics; fused families (AF05+)
        /// splat inline in the physics loop.
        pub fn step(self: *Self, dt: f32, fb: []u8, w: u32, h: u32) void {
            H.step(self, dt, fb, w, h);
            self.frame +%= 1; // AF01-blend hash RNG frame counter (free otherwise)
        }

        pub fn deinit(self: *Self) void {
            if (@hasDecl(H, "deinitExtra")) H.deinitExtra(self);
            self.data.deinit(self.alloc);
            self.alloc.destroy(self);
        }

        pub fn snapshot(self: *const Self, out: []f32) void {
            self.data.snapshot(out);
        }

        pub fn bytesPerParticle(self: *const Self) usize {
            const scratch: usize = if (@hasDecl(H, "scratchBytes")) H.scratchBytes(self) else 0;
            return self.data.bytesPerParticle() + scratch;
        }

        pub fn dumpFields(self: *const Self, alloc: std.mem.Allocator) ![]FieldDump {
            return self.data.dumpFields(alloc);
        }
    };
}
