#!/usr/bin/env python3
"""Prototype: analyze ONE cell → <cell>.json + <cell>.md.

Produces the per-cell analysis pair described in
`.scratch/plan/reporting-and-analysis.md` §2/§5 for a single cell, using:
  - runs.jsonl   (measured series)
  - hardware.json (cache hierarchy + streaming ceiling)
  - pmc.jsonl    (cycle attribution, if present)
  - assembly     (the cell's rebuilt binary → disassembly of `step`)

The <cell>.json is the structured evidence bundle (deterministic). The <cell>.md
is the narrative, generated by an LLM (z.ai / GLM, OpenAI-compatible) from the
evidence — Tier-2 narrative per plan decision 2.

Usage:
    scripts/analyze_cell.py L1.B1.w1-autovec.w2-opt            # full: json + md
    scripts/analyze_cell.py L1.B1.w1-autovec.w2-opt --json-only
    scripts/analyze_cell.py L1.B1.w1-autovec.w2-opt --prompt-only   # print the LLM prompt
    MODEL=glm-4.5 scripts/analyze_cell.py L1.B1.w1-autovec.w2-opt

LLM key: read from env ZAI_API_KEY, else file .scratch/zai_api_key (gitignored).
"""
from __future__ import annotations
import json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "experiments", "data")
ASM_CACHE = os.path.join(ROOT, ".scratch", "asm_cache")
DEFAULT_MODEL = "glm-5.2"
ADDR = re.compile(r"^[0-9a-f]{16}$")

# Death-rate points EXCLUDED from per-cell bundles (legacy sweep values not in
# experiments/sweeps/death_rates.txt). Raw data retains them. Keep in sync with
# build_report.py.
EXCLUDE_DEATH_Q = (0.0, 0.75)


def sh(cmd):
    return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True).stdout


def split_cell(cell):
    layout, strat = cell.split(".", 1)
    return layout, strat


def machine_id():
    ids = [d for d in os.listdir(DATA) if os.path.isdir(os.path.join(DATA, d))]
    if len(ids) != 1:
        sys.exit(f"expected one machine under {DATA}, found {ids}; pass -M <id>")
    return ids[0]


def load_jsonl(path, cell):
    out = []
    if not os.path.exists(path):
        return out
    for line in open(path):
        try:
            r = json.loads(line)
        except Exception:
            continue
        if r.get("cell") != cell:
            continue
        if r.get("death_q") in EXCLUDE_DEATH_Q:
            continue
        out.append(r)
    return out


def source_hash(cell):
    return sh([sys.executable, os.path.join(ROOT, "scripts", "cell_hash.py"), cell]).strip()


# ---- assembly: build (cached) + disassemble step ----

def ensure_binary(cell, shash):
    layout, strat = split_cell(cell)
    cache = os.path.join(ASM_CACHE, shash)
    binp = os.path.join(cache, "bin", f"{cell}.bench")
    if os.path.exists(binp):
        return binp, cache
    os.makedirs(cache, exist_ok=True)
    cmd = ["zig", "build", "-p", cache, f"-Dlayout={layout}", f"-Dstrat={strat}",
           "-Dmode=bench", "-Doptimize=ReleaseFast"]
    r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("build failed:\n" + (r.stderr or r.stdout)[-800:])
    return binp, cache


def step_symbol(strat):
    return f"_framework.sim.Strategy(layouts.L1.data.Data,layouts.L1.{strat}.H).step"


def disasm_step(binp, strat):
    sym = step_symbol(strat)
    nm = sh(["nm", binp])
    if sym not in nm:
        return None
    ot = sh(["otool", "-tV", binp]).splitlines()
    start = next((i + 1 for i, l in enumerate(ot)
                  if l.startswith("_") and l.rstrip().endswith(":") and sym in l), None)
    if start is None:
        return None
    body = []
    for l in ot[start:]:
        if l.startswith("_") and l.rstrip().endswith(":"):
            break
        body.append(l)
    return body


def histogram(body):
    from collections import Counter
    base = Counter()
    vector = 0
    for l in body:
        t = l.split()
        if len(t) < 2 or not ADDR.match(t[0]):
            continue
        m = t[1]
        base[m.split(".")[0]] += 1
        if "." in m and re.match(r"(2|3|4|8|16)[sdh]", m.split(".", 1)[1]):
            vector += 1
    return dict(base.most_common()), vector


# ---- godbolt source↔asm attribution (reporting-and-analysis.md §5.5/§12.4) ----
# The same ReleaseFast codegen, built strip=false + dsymutil, lets llvm-objdump
# --source attribute each asm address to its source line. llvm-objdump garbles
# the Mach-O arm64 *decode* (<unknown>), so we take ADDRESSES + SOURCE from it
# and the clean asm from otool, joined on address. Cached in bin-debug/.

OBJDUMP = ["xcrun", "llvm-objdump"]


def ensure_debug_binary(cell, shash):
    """Build the strip=false (same ReleaseFast codegen) variant + its dSYM.
    Cached at asm_cache/<shash>/bin-debug/. Returns (binp, dwarffile) or (None,None)."""
    layout, _ = split_cell(cell)
    cache = os.path.join(ASM_CACHE, shash)
    dbgprefix = os.path.join(cache, "bin-debug")
    binp = os.path.join(dbgprefix, "bin", f"{cell}.bench")
    dwarffile = os.path.join(dbgprefix, "dod.dSYM", "Contents", "Resources", "DWARF", f"{cell}.bench")
    if os.path.exists(dwarffile):
        return binp, dwarffile
    cmd = ["zig", "build", "-p", dbgprefix, f"-Dlayout={layout}", f"-Dstrat={cell.split('.',1)[1]}",
           "-Dmode=bench", "-Doptimize=ReleaseFast", "-Dkeep-debug=true"]
    if subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True).returncode != 0:
        return None, None
    subprocess.run(["dsymutil", binp, "-o", os.path.join(dbgprefix, "dod.dSYM")],
                   capture_output=True, text=True)
    return (binp, dwarffile) if os.path.exists(dwarffile) else (None, None)


def step_addr_range(binp, strat):
    """(start, stop) of the step symbol via nm. Commas in the mangled name break
    --disassemble-symbols' comma-list parsing, so callers use address ranges."""
    sym = step_symbol(strat)
    start, addrs = None, []
    for l in sh(["nm", binp]).splitlines():
        p = l.split()
        if len(p) < 2:
            continue
        if p[-1] == sym:
            start = int(p[0], 16)
        if p[1] in ("t", "T"):
            addrs.append(int(p[0], 16))
    if start is None:
        return None, None
    addrs.sort()
    return start, next((a for a in addrs if a > start), start + 0x800)


def source_map(dwarffile, start, stop):
    """{addr_int: source_line} from llvm-objdump --source. Source lines are
    ';'-comments, attributed to the addresses that follow until the next one."""
    r = subprocess.run(OBJDUMP + ["--source", f"--start-address=0x{start:x}",
                                  f"--stop-address=0x{stop:x}", dwarffile],
                       capture_output=True, text=True)
    out, cur = {}, None
    for l in r.stdout.splitlines():
        s = l.strip()
        if s.startswith(";"):
            cur = s[1:].strip() or cur
        elif (m := re.match(r"^([0-9a-f]+):", s)):
            out[int(m.group(1), 16)] = cur
    return out


def cell_source(cell, groups):
    """The cell's own source file (what the user wrote), plus a per-group map to
    the line number in that file (None for inlined library code). The SPA shows
    this real, properly-formatted source on the left and links asm blocks to
    source lines (click/hover)."""
    try:
        import cell_hash
    except ImportError:
        return None
    path = cell_hash.cell_file_path(cell)
    try:
        lines = open(path, encoding="utf-8").read().splitlines()
    except OSError:
        return None
    textline = {}
    for i, s in enumerate(lines, 1):
        key = s.strip()
        if key and key not in textline:
            textline[key] = i
    group_lines = [textline.get((g.get("source") or "").strip()) for g in groups]
    return {"file": os.path.relpath(path, ROOT), "lines": lines, "group_lines": group_lines}


def reindent_sources(cell, groups):
    """llvm-objdump mangles each source line's leading whitespace, so recover
    the real indentation: match the stripped source text to its line in the
    cell's @import closure (cell_hash walks it) and use that file line verbatim.
    Unmatched lines fall back flush-left (cleaner than llvm's mangled prefix)."""
    try:
        import cell_hash
    except ImportError:
        return groups
    closure = cell_hash.walk_closure(cell_hash.cell_file_path(cell))
    lookup = {}
    for f in closure:
        try:
            for raw in open(f, encoding="utf-8"):
                s = raw.rstrip("\n")
                key = s.strip()
                if key and key not in lookup:
                    lookup[key] = s          # the full line, real indentation intact
        except OSError:
            continue
    for g in groups:
        key = (g.get("source") or "").strip()
        g["source"] = lookup.get(key, key)  # matched: real indent; else flush-left
    return groups


def attributed_asm(cell, shash, strat, otool_body):
    """Godbolt grouping [{source, asm:[...]}]: otool gives the clean asm (by
    address), llvm-objdump --source gives each address's source line. None if
    the debug build / toolchain is unavailable (SPA falls back to flat listing)."""
    binp, dwarffile = ensure_debug_binary(cell, shash)
    if not binp:
        return None
    start, stop = step_addr_range(binp, strat)
    if start is None:
        return None
    smap = source_map(dwarffile, start, stop)
    if not smap:
        return None
    groups, cur_src, cur_asm = [], None, []
    for line in otool_body:
        t = line.split("\t")
        if len(t) < 2 or not ADDR.match(t[0]):
            continue
        src = smap.get(int(t[0], 16), cur_src)
        if src != cur_src and cur_asm:
            groups.append({"source": cur_src or "", "asm": cur_asm}); cur_asm = []
        cur_src = src
        cur_asm.append("\t".join(t[1:]).rstrip())
    if cur_asm:
        groups.append({"source": cur_src or "", "asm": cur_asm})
    return reindent_sources(cell, groups)


# ---- evidence bundle ----

def cache_transitions(bpp, hw):
    out = []
    for name, key in [("L1d", "l1dcachesize"), ("L2", "l2cachesize"), ("L3", "l3cachesize")]:
        sz = hw.get(key) or 0
        if sz:
            out.append([name, sz // bpp])
    return out


def series(runs, bpp):
    """min ns/particle per (death_q, N, threads); achieved_bw = bpp·N/ns_frame."""
    best = {}
    for r in runs:
        key = (r["death_q"], r["N"], r["threads"])
        cur = best.get(key)
        if cur is None or r["ns_particle"] < cur["ns_particle"]:
            best[key] = r
    grouped = {}
    for (q, N, T), r in sorted(best.items()):
        grouped.setdefault(q, []).append({
            "N": N, "threads": T,
            "ns_particle": round(r["ns_particle"], 3),
            "ns_frame": r["ns_frame"],
            "achieved_bw_gbs": round(bpp * N / r["ns_frame"], 2) if r["ns_frame"] else None,
        })
    return grouped


def build_evidence(cell, m, hw, runs, pmc, asm):
    bpp = runs[0]["bytes_per_particle"]
    decl = {k: runs[0][k] for k in
            ("blueprint", "ordering", "intermediates", "golden_class", "halide_expressible")}
    return {
        "cell": cell, "machine_id": m,
        "source_hash": asm["source_hash"], "git_sha": runs[0].get("git_sha"),
        "layout": runs[0]["layout"], "bytes_per_particle": bpp,
        "cell_decl": decl,
        "hardware": {k: hw[k] for k in
                     ("cpu", "l1dcachesize", "l2cachesize", "l3cachesize",
                      "cachelinesize", "streaming_bw_gbs", "logicalcpu")},
        "cache_transitions": cache_transitions(bpp, hw),
        "series": series(runs, bpp),
        "pmc": [{k: p[k] for k in ("N", "death_q", "trial", "cycles",
                 "useful_pct", "processing_pct", "delivery_pct", "discarded_pct")}
                for p in pmc],
        "asm": asm,
    }


# ---- LLM narrative (z.ai, OpenAI-compatible) ----

SYSTEM = """You are a performance engineer writing the analysis for ONE cell of a \
particle-simulation benchmark, measured on ONE machine. You are given a structured \
evidence bundle: the cell's declaration, its hypothesis, the measured ns/particle \
and achieved bandwidth across N and death-rate, the machine's cache hierarchy and \
streaming-bandwidth ceiling, PMC cycle attribution, and the disassembly of the \
cell's `step` function with an instruction histogram.

The narrative's JOB is to evaluate the cell's hypothesis against the measurements. \
Do NOT restate the declaration (blueprint / ordering / intermediates / golden / \
walk-axes) — the reader already has it. Write markdown with EXACTLY these five \
sections, in order, each one a tight paragraph:

## Intent
ONE sentence: the hypothesis this cell exists to test. Start with "Hypothesis:". \
Nothing else. Example: "Hypothesis: compiler auto-vectorization over per-particle \
components can approach the streaming ceiling on death-free workloads."

## Cache saturation
Read the ns/particle-vs-N curve across death rates. The bundle gives the L1d and \
L2 spill points as N values — locate them on the curve and state whether cost \
RISES, FALLS, or stays FLAT at each spill. Explain the SHAPE in those terms: \
overhead amortization at small N? a knee at the L2→DRAM spill? death-rate raising \
the floor without changing the N-shape? Cite the specific N values and ns/p \
numbers. If the hypothesis concerns cache behavior, address it here.

## Bandwidth
Peak achieved GB/s, what % of the streaming ceiling, at which N and death rate. \
State the verdict — bandwidth-bound, compute-bound, or overhead-bound — and WHERE \
it transitions (by N or by death rate). If the hypothesis predicts approaching the \
streaming ceiling, say how close it got and at which regime; if it falls away, say \
when and why (e.g. branchy-respawn cost rising with churn). Cite the numbers.

## Assembly
Did the compiler vectorize? Across the components of one particle, or across \
particles? Is there a gather (an indexed NEON load like `ld1.s {vN}[i]`)? Cite \
specific instructions (e.g. `ldr q`, `fmul.4s`, `ext.16b`, `uqadd.8b`) and connect \
the codegen to the cache/bandwidth findings — e.g. "component-wise vec on stride-17 \
explains the high bandwidth; the scatter's byte stores cap it at 46% of ceiling."

## Verdict
Explicitly: did the hypothesis hold? Cite the two or three numbers that decide it. \
Example forms:
  - "Holds — at q=0 the cell sustains 22.7 GB/s = 90% of ceiling with no \
cache-spill knee, confirming autovec approaches the streaming ceiling on \
death-free workloads."
  - "Partially — bandwidth-bound and near-ceiling at q≤0.05, but the branchy \
respawn collapses it to 35% of ceiling by q=0.25, so the hypothesis only holds \
in the low-churn regime."
  - "Refuted — achieved never exceeds 46% of ceiling because the fused scatter's \
byte-granular writes cannot stream, regardless of death rate."
One tight paragraph.

HARD RULES:
- Cite ONLY numbers and instructions present in the evidence. Never invent.
- If the evidence is silent on something, say so explicitly.
- No marketing voice, no "in conclusion". ~300–350 words total.
- Output ONLY the five ## sections. No preamble, no code fence."""


def evidence_to_prompt(e):
    hw = e["hardware"]
    ct = e["cache_transitions"]
    lines = [
        f"CELL: {e['cell']}",
        f"MACHINE: {e['machine_id']} ({hw['cpu']})",
        "HARDWARE:",
        f"  l1dcachesize={hw['l1dcachesize']}  l2cachesize={hw['l2cachesize']}  "
        f"l3cachesize={hw['l3cachesize']}  cachelinesize={hw['cachelinesize']}",
        f"  streaming_bw_gbs={hw['streaming_bw_gbs']}  logicalcpu={hw['logicalcpu']}",
        "CELL_DECL:",
        f"  blueprint={e['cell_decl']['blueprint']}  ordering={e['cell_decl']['ordering']}  "
        f"intermediates={e['cell_decl']['intermediates']}  golden={e['cell_decl']['golden_class']}",
        f"  bytes_per_particle={e['bytes_per_particle']}",
        f"  halide_expressible: {e['cell_decl']['halide_expressible']}",
        f"CACHE TRANSITIONS (working set = {e['bytes_per_particle']}·N):",
        "  " + "  ".join(f"{n} spill at N≈{v}" for n, v in ct) or "  (none)",
        "SERIES (min ns/particle across trials; achieved_bw = bytes/p·N / ns_frame):",
    ]
    for q, rows in e["series"].items():
        lines.append(f"  death_q={q}:")
        for r in rows:
            bw = f"{r['achieved_bw_gbs']} GB/s" if r["achieved_bw_gbs"] is not None else "?"
            lines.append(f"    N={r['N']:<9} ns/p={r['ns_particle']:<7} achieved={bw}")
    if e["pmc"]:
        for p in e["pmc"]:
            lines.append(
                f"PMC (N={p['N']}, death_q={p['death_q']}): cycles={p['cycles']}  "
                f"useful={p['useful_pct']}%  processing={p['processing_pct']}%  "
                f"delivery={p['delivery_pct']}%  discarded={p['discarded_pct']}%")
    else:
        lines.append("PMC: (none)")
    a = e["asm"]
    lines.append(f"DISASSEMBLY of `step` ({a['n_instructions']} insns), histogram:")
    lines.append("  " + "  ".join(f"{k}={v}" for k, v in a["histogram"].items()))
    lines.append(f"  vector-suffixed instructions: {a['vector_insns']}")
    lines.append("EXCERPT (full step body):")
    lines.append(a["excerpt"])
    return "\n".join(lines)


def read_key():
    k = os.environ.get("ZAI_API_KEY", "").strip()
    if k:
        return k
    f = os.path.join(ROOT, ".scratch", "zai_api_key")
    if os.path.exists(f):
        return open(f).read().strip()
    return None


def read_base_url():
    """Optional dedicated endpoint (GLM Coding Plan keys use one instead of
    the default api.z.ai). Set via env ZAI_BASE_URL or .scratch/zai_base_url."""
    v = os.environ.get("ZAI_BASE_URL", "").strip()
    if v:
        return v
    f = os.path.join(ROOT, ".scratch", "zai_base_url")
    if os.path.exists(f):
        return open(f).read().strip()
    return None


def llm_narrate(prompt, model):
    key = read_key()
    if not key:
        sys.exit("no ZAI_API_KEY in env or .scratch/zai_api_key; use --json-only/--prompt-only")
    try:
        from zai import ZaiClient
    except ImportError:
        sys.exit("zai-sdk not installed; run `uv add zai-sdk` (or `uv sync`)")
    client = ZaiClient(api_key=key, base_url=read_base_url())
    try:
        # GLM-5.2 is a reasoning model: reasoning tokens count toward
        # max_tokens. The budget varies 2k–8k reasoning + ~5k visible, so 8000
        # is too tight at the high end (a cell can finish=length with empty
        # visible output). Default 16000 leaves headroom; override per-run.
        max_tokens = int(os.environ.get("MAX_TOKENS", "16000"))
        resp = client.chat.completions.create(
            model=model, temperature=0.3, max_tokens=max_tokens,
            messages=[{"role": "system", "content": SYSTEM},
                      {"role": "user", "content": prompt}])
        # GLM-5.2 is a reasoning model: reasoning tokens count toward max_tokens,
        # so log the split to catch truncation (finish=length means raise max_tokens).
        ch = resp.choices[0]
        u = resp.usage
        rt = getattr(getattr(u, "completion_tokens_details", None), "reasoning_tokens", None) if u else None
        print(f"  z.ai: finish={ch.finish_reason}  reasoning_tokens={rt}  "
              f"completion={getattr(u, 'completion_tokens', None)}", file=sys.stderr)
        return ch.message.content
    except Exception as e:
        # surface API errors (balance/auth/rate) with their body, not a bare traceback
        detail = getattr(getattr(e, "response", None), "text", None) or str(e)
        sys.exit(f"z.ai call failed ({model}): {detail[:500]}")


def is_layout_id(s):
    import re
    return bool(re.fullmatch(r"L\d+", s))


def read_layout_cells(layout):
    """experiments/sweeps/<layout>.cells -> full cell names, as-is
    (the file already stores 'L1.<strat>' lines; comments/blanks skipped)."""
    p = os.path.join(ROOT, "experiments", "sweeps", f"{layout}.cells")
    return [c.strip() for c in open(p)
            if c.strip() and not c.strip().startswith("#")]


def process_cell(cell, m, hw, model, json_only, prompt_only, force=False):
    layout, strat = split_cell(cell)
    runs = load_jsonl(os.path.join(DATA, m, "runs.jsonl"), cell)
    pmc = load_jsonl(os.path.join(DATA, m, "pmc.jsonl"), cell)
    if not runs:
        print(f"  no runs for {cell} — skip", file=sys.stderr)
        return "skip"
    shash = source_hash(cell)
    binp, _ = ensure_binary(cell, shash)
    body = disasm_step(binp, strat) or []
    hist, vec = histogram(body)
    asm = {"source_hash": shash, "symbol": step_symbol(strat),
           "n_instructions": len(body), "histogram": hist, "vector_insns": vec,
           "excerpt": "\n".join(body)}
    src = attributed_asm(cell, shash, strat, body)
    if src is not None:
        asm["source_attributed"] = src
        cs = cell_source(cell, src)
        if cs:
            asm["cell_source"] = cs
    evidence = build_evidence(cell, m, hw, runs, pmc, asm)
    outdir = os.path.join(ROOT, "experiments", "analysis", m, layout)
    os.makedirs(outdir, exist_ok=True)
    jpath = os.path.join(outdir, f"{strat}.json")
    mpath = os.path.join(outdir, f"{strat}.md")
    new_json = json.dumps(evidence, indent=2)
    old_json = open(jpath).read() if os.path.exists(jpath) else None
    if old_json != new_json:
        with open(jpath, "w") as f:
            f.write(new_json)
        print(f"  wrote {jpath}  ({len(body)} insn, {len(runs)} runs)", file=sys.stderr)
    else:
        print(f"  {os.path.basename(jpath)} unchanged — skip write", file=sys.stderr)
    prompt = evidence_to_prompt(evidence)
    if prompt_only:
        print(prompt)
        return "ok"
    if json_only:
        return "ok"
    if os.path.exists(mpath) and not force:
        print(f"  {os.path.basename(mpath)} exists — skip (--force to regenerate)", file=sys.stderr)
        return "skip"
    md = llm_narrate(prompt, model)
    with open(mpath, "w") as f:
        f.write(f"<!-- auto-generated by scripts/analyze_cell.py ({model}); "
                f"source_hash={shash} -->\n\n" + md.strip() + "\n")
    print(f"  wrote {mpath}", file=sys.stderr)
    return "ok"


# ---- --verify: integrity check (narrative cites only bundle evidence) ----

SECTIONS = ["## Intent", "## Cache saturation", "## Bandwidth", "## Assembly", "## Verdict"]

# AArch64 mnemonic allowlist. A backticked token is only treated as a cited
# instruction if its base is in here — so `spawn` (a function symbol) or
# English words aren't mistaken for instructions. Keep loose; missing one just
# means a citation isn't checked, never a false flag.
MNEMONICS = frozenset("""
ldr str ldp stp ldur stur
ld1 ld2 ld3 ld4 st1 st2 st3 st4
fmov fadd fsub fmul fdiv fmla fmls fmin fmax fneg fabs fsqrt fcmp fcsel
fcvt scvtf ucvtf fcvtzs fcvtns fcvtas frintm frintp frintz
dup ext ins umov smov movi mvni ushr sshr shl usra ssra xtn
sqadd uqadd sqsub uqsub tbl tbx rev16 rev32 rev64 uzp1 uzp2 zip1 zip2 trn1 trn2
add sub mul mla mls umull smull udiv sdiv madd msub
cmp cmn tst neg mvn and orr eor bic orn lsl lsr asr ror
sbfx ubfx bfi bfxil sxth sxtw uxth uxtw sxtb uxtb adrp adr
b bl br ret cbz cbnz tbz tbnz
csel cset cinc csinc ccmp ccmn
rev clz cls rbit mov movz movk
""".split())

# Preceding-context words that mean the narrative cites an instruction's
# ABSENCE ("no `ld1` gather present") — correct, not a hallucination.
NEG_WORDS = ("no ", "not ", "without ", "absent", "absence", "zero ", "none",
             "lacks", "lack of", "neither", "nor ", "0 ")


def attested_numbers(e):
    """Every number the narrative may legitimately cite: raw values + common
    derivations (roundings; cache sizes in KB/MB; footprint in KB/MB; % of
    streaming ceiling; histogram counts)."""
    nums = set()

    def add(x):
        try:
            f = float(x)
        except (TypeError, ValueError):
            return
        for r in (3, 2, 1, 0):
            nums.add(round(f, r))
        nums.add(int(f))

    bpp = e["bytes_per_particle"]
    add(bpp)
    hw = e["hardware"]
    ceil = hw["streaming_bw_gbs"]
    for k in ("l1dcachesize", "l2cachesize", "l3cachesize",
              "cachelinesize", "logicalcpu", "streaming_bw_gbs"):
        v = hw.get(k) or 0
        add(v)
        if k.endswith("cachesize") and v:
            add(v / 1024)             # KB
            add(v / (1024 * 1024))    # MB
    for _, n in e["cache_transitions"]:
        add(n)
    for q, rows in e["series"].items():
        add(float(q))
        for r in rows:
            add(r["N"])
            add(r["ns_particle"])
            if r.get("achieved_bw_gbs") is not None and ceil:
                add(r["achieved_bw_gbs"])
                add(r["achieved_bw_gbs"] / ceil * 100)   # % of ceiling
            add(r["N"] * bpp / 1e6)          # footprint MB
            add(r["N"] * bpp / 1024)         # footprint KB
    for p in e["pmc"]:
        for k in ("cycles", "useful_pct", "processing_pct",
                 "delivery_pct", "discarded_pct"):
            add(p.get(k))
    for c in e["asm"]["histogram"].values():
        add(c)
    add(e["asm"]["n_instructions"])          # "... instructions" citations
    if hw.get("cachelinesize"):
        add(hw["cachelinesize"] / 8)         # cacheline in bytes (128b -> 16B)
    return nums


def cited_mnemonics(md):
    """(base, negated) for backticked spans whose base is a real AArch64
    mnemonic. `negated` = a negation word precedes the span, i.e. the narrative
    cites the instruction's ABSENCE (correct, not a hallucination)."""
    out = []
    for m in re.finditer(r"`([^`]+)`", md):
        tok = m.group(1).strip().split()
        if not tok:
            continue
        base = re.split(r"[.\s]", tok[0])[0].lower()
        if base not in MNEMONICS:
            continue
        ctx = md[max(0, m.start() - 24):m.start()].lower()
        out.append((base, any(neg in ctx for neg in NEG_WORDS)))
    return out


def prose_numbers(md):
    """Floats + ints (>=4) from prose, with HTML comments (the glm-5.2 /
    source_hash header) and backticked spans removed."""
    s = re.sub(r"<!--.*?-->", " ", md, flags=re.S)
    s = re.sub(r"`[^`]*`", " ", s)
    s = re.sub(r"\b0x[0-9a-fA-F]+\b", " ", s)   # hex addresses (0x100055634)
    out = []
    for m in re.finditer(r"\d+\.\d+|\d+", s):
        tok = m.group()
        if "." not in tok and int(tok) < 4:
            continue
        out.append(float(tok))
    return out


def verify_cell(cell, m):
    layout, strat = split_cell(cell)
    base = os.path.join(ROOT, "experiments", "analysis", m, layout)
    jpath = os.path.join(base, f"{strat}.json")
    mpath = os.path.join(base, f"{strat}.md")
    if not os.path.exists(jpath):
        return "MISS", ["no .json bundle"], []
    if not os.path.exists(mpath):
        return "MISS", ["no .md narrative"], []
    e = json.load(open(jpath))
    md = open(mpath).read()
    errs = []
    for s in SECTIONS:
        if s not in md:
            errs.append(f"missing section {s!r}")
    hist = {k.lower() for k in e["asm"]["histogram"]}
    for b, neg in cited_mnemonics(md):
        if not neg and b not in hist:
            errs.append(f"cited instruction `{b}` not in asm histogram")
    attested = attested_numbers(e)
    unmatched = sorted({round(n, 3) for n in prose_numbers(md)
                        if not any(abs(n - a) <= max(0.05, abs(a) * 0.01) for a in attested)})
    return ("FAIL" if errs else "OK"), errs, unmatched


def run_verify(target, m, json_out=None):
    cells = [target] if not is_layout_id(target) else read_layout_cells(target)
    print(f"=== verify: {len(cells)} cells ===", file=sys.stderr)
    fails = 0
    results = {}
    for i, c in enumerate(cells, 1):
        status, errs, unmatched = verify_cell(c, m)
        results[c] = {"status": status, "errors": errs, "unmatched": unmatched}
        flag = {"OK": "OK  ", "FAIL": "FAIL", "MISS": "MISS"}[status]
        extra = f"  unverified_nums={unmatched[:8]}" if unmatched else ""
        print(f"[{i}/{len(cells)}] {flag} {c}{extra}", file=sys.stderr)
        for e in errs:
            print(f"           - {e}", file=sys.stderr)
        if status == "FAIL":
            fails += 1
    print(f"=== verify done: {fails} FAIL of {len(cells)} ===", file=sys.stderr)
    if json_out:
        import json as _json
        with open(json_out, "w") as f:
            _json.dump(results, f, indent=2)
        print(f"  (wrote {json_out})", file=sys.stderr)
    return 1 if fails else 0


def main():
    argv = sys.argv[1:]
    json_only = "--json-only" in argv
    prompt_only = "--prompt-only" in argv
    force = "--force" in argv
    verify_mode = "--verify" in argv
    json_out = None
    if "--verify-json" in argv:
        i = argv.index("--verify-json")
        json_out = argv[i + 1] if i + 1 < len(argv) else None
        del argv[i:i + 2]
    argv = [a for a in argv if not a.startswith("--") and not a.startswith("-")]
    target = argv[0] if argv else "L1.B1.w1-autovec.w2-opt"
    model = os.environ.get("MODEL", DEFAULT_MODEL)
    m = machine_id()
    if verify_mode:
        sys.exit(run_verify(target, m, json_out=json_out))
    hw = json.load(open(os.path.join(DATA, m, "hardware.json")))
    if is_layout_id(target):
        cells = read_layout_cells(target)
        print(f"=== layout {target}: {len(cells)} cells (model {model}) ===", file=sys.stderr)
        ok = skip = fail = 0
        for i, c in enumerate(cells, 1):
            print(f"[{i}/{len(cells)}] {c}", file=sys.stderr)
            try:
                st = process_cell(c, m, hw, model, json_only, prompt_only, force)
                if st == "skip":
                    skip += 1
                else:
                    ok += 1
            except SystemExit as e:
                print(f"  !! FAIL {c}: {e}", file=sys.stderr)
                fail += 1
        print(f"=== done: {ok} ok, {skip} skip, {fail} fail (of {len(cells)}) ===", file=sys.stderr)
    else:
        process_cell(target, m, hw, model, json_only, prompt_only, force)


if __name__ == "__main__":
    main()
