#!/usr/bin/env python3
"""Prototype: analyze ONE algo → <algo>.json + <algo>.md.

Produces the per-algo analysis pair described in
`.scratch/plan/reporting-and-analysis.md` §2/§5 for a single algo, using:
  - <algo>.runs.jsonl  (measured timing + check rows)
  - hardware.json      (cache hierarchy + streaming ceiling)
  - <algo>.profile.jsonl (cycle attribution, if collected)
  - <algo>.json        (the asm bundle — captured disassembly of `step`, written by algo.py)

The <algo>.json is the structured evidence bundle (deterministic). The <algo>.md
is the narrative, generated by an LLM (z.ai / GLM, OpenAI-compatible) from the
evidence — Tier-2 narrative per plan decision 2.

Usage:
    scripts/analyze_algo.py ML01.AF02.LP1-autovec.LP2-opt            # full: json + md
    scripts/analyze_algo.py ML01.AF02.LP1-autovec.LP2-opt --json-only
    scripts/analyze_algo.py ML01.AF02.LP1-autovec.LP2-opt --prompt-only   # print the LLM prompt
    MODEL=glm-4.5 scripts/analyze_algo.py ML01.AF02.LP1-autovec.LP2-opt

LLM key: read from env ZAI_API_KEY, else file .scratch/zai_api_key (gitignored).
"""
from __future__ import annotations
import json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "experiments", "data")
ASM_CACHE = os.path.join(ROOT, ".scratch", "asm_cache")
DEFAULT_MODEL = "glm-5.2"
ADDR = re.compile(r"^[0-9a-f]{16}$")

# Death-rate points EXCLUDED from per-algo bundles (legacy sweep values not in
# experiments/sweeps/death_rates.txt). Raw data retains them. Keep in sync with
# build_report.py.
EXCLUDE_DEATH_Q = (0.0, 0.75)

# Particle counts (N) EXCLUDED from per-algo bundles — legacy sweep points
# retired from the bench SWEEP (see build_report.py). Keep in sync.
EXCLUDE_N = (16000,)


def sh(cmd):
    return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True).stdout


def split_algo(algo):
    mem_layout, algo_part = algo.split(".", 1)
    return mem_layout, algo_part


def machine_id():
    ids = [d for d in os.listdir(DATA) if os.path.isdir(os.path.join(DATA, d))]
    if len(ids) != 1:
        sys.exit(f"expected one machine under {DATA}, found {ids}; pass -M <id>")
    return ids[0]


def load_jsonl(path, algo=None, kind=None, source_hash=None):
    """Load a per-algo JSONL file. `algo`/`kind`/`source_hash` are optional row
    filters (a per-algo file is already one algo, so `algo` is usually redundant).
    `source_hash` keeps only rows pinned to the current source — drops
    pre-versioning null rows + any stale-source rows so the report never mixes
    measurement epochs. Applies EXCLUDE_DEATH_Q / EXCLUDE_N."""
    out = []
    if not os.path.exists(path):
        return out
    for line in open(path):
        try:
            r = json.loads(line)
        except Exception:
            continue
        if algo is not None and r.get("algo") != algo:
            continue
        if kind is not None and r.get("kind") != kind:
            continue
        if source_hash is not None and r.get("source_hash") != source_hash:
            continue
        if r.get("death_q") in EXCLUDE_DEATH_Q:
            continue
        if r.get("N") in EXCLUDE_N:
            continue
        out.append(r)
    return out


def source_hash(algo):
    return sh([sys.executable, os.path.join(ROOT, "scripts", "algo_hash.py"), algo]).strip()


# ---- evidence bundle ----

def cache_transitions(bpp, hw):
    out = []
    for name, key in [("L1d", "l1dcachesize"), ("L2", "l2cachesize"), ("L3", "l3cachesize")]:
        sz = hw.get(key) or 0
        if sz:
            out.append([name, sz // bpp])
    return out


def series(runs, bpp):
    """min ns/particle per (death_q, N, threads); achieved_bw = bpp·N/ns_frame."""
    best = {}
    for r in runs:
        key = (r["death_q"], r["N"], r["threads"])
        cur = best.get(key)
        if cur is None or r["ns_particle"] < cur["ns_particle"]:
            best[key] = r
    grouped = {}
    for (q, N, T), r in sorted(best.items()):
        grouped.setdefault(q, []).append({
            "N": N, "threads": T,
            "ns_particle": round(r["ns_particle"], 3),
            "ns_frame": r["ns_frame"],
            "achieved_bw_gbs": round(bpp * N / r["ns_frame"], 2) if r["ns_frame"] else None,
        })
    return grouped


def build_evidence(algo, m, hw, runs, prof, asm):
    bpp = runs[0]["bytes_per_particle"]
    decl = {k: runs[0][k] for k in
            ("algo_fam", "ordering", "intermediates", "golden_class", "halide_expressible")}
    return {
        "algo": algo, "machine_id": m,
        "source_hash": asm["source_hash"], "git_sha": runs[0].get("git_sha"),
        "mem_layout": runs[0]["mem_layout"], "bytes_per_particle": bpp,
        "algo_meta": decl,
        "hardware": {k: hw[k] for k in
                     ("cpu", "l1dcachesize", "l2cachesize", "l3cachesize",
                      "cachelinesize", "streaming_bw_gbs", "logicalcpu")},
        "cache_transitions": cache_transitions(bpp, hw),
        "series": series(runs, bpp),
        "profile": [{k: p.get(k) for k in ("N", "death_q", "threads", "trial", "profiler",
                 "cycles", "compute_pct", "backend_stall_pct",
                 "frontend_stall_pct", "branch_flush_pct")}
                for p in prof],
        "asm": asm,
    }


# ---- LLM narrative (z.ai, OpenAI-compatible) ----

SYSTEM = """You are a performance engineer writing the analysis for ONE algo of a \
particle-simulation benchmark, measured on ONE machine. You are given a structured \
evidence bundle: the algo's declaration, its hypothesis, the measured ns/particle \
and achieved bandwidth across N and death-rate, the machine's cache hierarchy and \
streaming-bandwidth ceiling, cycle attribution (compute/backend/frontend/branch buckets), and the disassembly of the \
algo's `step` function with an instruction histogram.

The narrative's JOB is to evaluate the algo's hypothesis against the measurements. \
Do NOT restate the declaration (algo_fam / ordering / intermediates / golden / \
loop-axes) — the reader already has it. Write markdown with EXACTLY these five \
sections, in order, each one a tight paragraph:

## Intent
ONE sentence: the hypothesis this algo exists to test. Start with "Hypothesis:". \
Nothing else. Example: "Hypothesis: compiler auto-vectorization over per-particle \
components can approach the streaming ceiling on death-free workloads."

## Cache saturation
Read the ns/particle-vs-N curve across death rates. The bundle gives the L1d and \
L2 spill points as N values — locate them on the curve and state whether cost \
RISES, FALLS, or stays FLAT at each spill. Explain the SHAPE in those terms: \
overhead amortization at small N? a knee at the L2→DRAM spill? death-rate raising \
the floor without changing the N-shape? Cite the specific N values and ns/p \
numbers. If the hypothesis concerns cache behavior, address it here.

## Bandwidth
Peak achieved GB/s, what % of the streaming ceiling, at which N and death rate. \
State the verdict — bandwidth-bound, compute-bound, or overhead-bound — and WHERE \
it transitions (by N or by death rate). If the hypothesis predicts approaching the \
streaming ceiling, say how close it got and at which regime; if it falls away, say \
when and why (e.g. branchy-respawn cost rising with churn). Cite the numbers.

## Assembly
Did the compiler vectorize? Across the components of one particle, or across \
particles? Is there a gather (an indexed NEON load like `ld1.s {vN}[i]`)? Cite \
specific instructions (e.g. `ldr q`, `fmul.4s`, `ext.16b`, `uqadd.8b`) and connect \
the codegen to the cache/bandwidth findings — e.g. "component-wise vec on stride-17 \
explains the high bandwidth; the scatter's byte stores cap it at 46% of ceiling."

## Verdict
Explicitly: did the hypothesis hold? Cite the two or three numbers that decide it. \
Example forms:
  - "Holds — at q=0 the algo sustains 22.7 GB/s = 90% of ceiling with no \
cache-spill knee, confirming autovec approaches the streaming ceiling on \
death-free workloads."
  - "Partially — bandwidth-bound and near-ceiling at q≤0.05, but the branchy \
respawn collapses it to 35% of ceiling by q=0.25, so the hypothesis only holds \
in the low-churn regime."
  - "Refuted — achieved never exceeds 46% of ceiling because the fused scatter's \
byte-granular writes cannot stream, regardless of death rate."
One tight paragraph.

HARD RULES:
- Cite ONLY numbers and instructions present in the evidence. Never invent.
- If the evidence is silent on something, say so explicitly.
- No marketing voice, no "in conclusion". ~300–350 words total.
- Output ONLY the five ## sections. No preamble, no code fence."""


def evidence_to_prompt(e):
    hw = e["hardware"]
    ct = e["cache_transitions"]
    lines = [
        f"CELL: {e['algo']}",
        f"MACHINE: {e['machine_id']} ({hw['cpu']})",
        "HARDWARE:",
        f"  l1dcachesize={hw['l1dcachesize']}  l2cachesize={hw['l2cachesize']}  "
        f"l3cachesize={hw['l3cachesize']}  cachelinesize={hw['cachelinesize']}",
        f"  streaming_bw_gbs={hw['streaming_bw_gbs']}  logicalcpu={hw['logicalcpu']}",
        "CELL_DECL:",
        f"  algo_fam={e['algo_meta']['algo_fam']}  ordering={e['algo_meta']['ordering']}  "
        f"intermediates={e['algo_meta']['intermediates']}  golden={e['algo_meta']['golden_class']}",
        f"  bytes_per_particle={e['bytes_per_particle']}",
        f"  halide_expressible: {e['algo_meta']['halide_expressible']}",
        f"CACHE TRANSITIONS (working set = {e['bytes_per_particle']}·N):",
        "  " + "  ".join(f"{n} spill at N≈{v}" for n, v in ct) or "  (none)",
        "SERIES (min ns/particle across trials; achieved_bw = bytes/p·N / ns_frame):",
    ]
    for q, rows in e["series"].items():
        lines.append(f"  death_q={q}:")
        for r in rows:
            bw = f"{r['achieved_bw_gbs']} GB/s" if r["achieved_bw_gbs"] is not None else "?"
            lines.append(f"    N={r['N']:<9} ns/p={r['ns_particle']:<7} achieved={bw}")
    if e["profile"]:
        for p in e["profile"]:
            lines.append(
                f"PROFILE (N={p['N']}, death_q={p['death_q']}, threads={p.get('threads')}, "
                f"via {p.get('profiler', '?')}): cycles={p['cycles']}  "
                f"compute={p['compute_pct']}%  backend_stall={p['backend_stall_pct']}%  "
                f"frontend_stall={p['frontend_stall_pct']}%  branch_flush={p['branch_flush_pct']}%")
    else:
        lines.append("PROFILE: (none)")
    a = e["asm"]
    lines.append(f"DISASSEMBLY of `step` ({a['n_instructions']} insns), histogram:")
    lines.append("  " + "  ".join(f"{k}={v}" for k, v in a["histogram"].items()))
    lines.append(f"  vector-suffixed instructions: {a['vector_insns']}")
    lines.append("EXCERPT (full step body):")
    lines.append(a["excerpt"])
    return "\n".join(lines)


def read_key():
    k = os.environ.get("ZAI_API_KEY", "").strip()
    if k:
        return k
    f = os.path.join(ROOT, ".scratch", "zai_api_key")
    if os.path.exists(f):
        return open(f).read().strip()
    return None


def read_base_url():
    """Optional dedicated endpoint (GLM Coding Plan keys use one instead of
    the default api.z.ai). Set via env ZAI_BASE_URL or .scratch/zai_base_url."""
    v = os.environ.get("ZAI_BASE_URL", "").strip()
    if v:
        return v
    f = os.path.join(ROOT, ".scratch", "zai_base_url")
    if os.path.exists(f):
        return open(f).read().strip()
    return None


def llm_narrate(prompt, model):
    key = read_key()
    if not key:
        sys.exit("no ZAI_API_KEY in env or .scratch/zai_api_key; use --json-only/--prompt-only")
    try:
        from zai import ZaiClient
    except ImportError:
        sys.exit("zai-sdk not installed; run `uv add zai-sdk` (or `uv sync`)")
    client = ZaiClient(api_key=key, base_url=read_base_url())
    try:
        # GLM-5.2 is a reasoning model: reasoning tokens count toward
        # max_tokens. The budget varies 2k–8k reasoning + ~5k visible, so 8000
        # is too tight at the high end (a algo can finish=length with empty
        # visible output). Default 16000 leaves headroom; override per-run.
        max_tokens = int(os.environ.get("MAX_TOKENS", "16000"))
        resp = client.chat.completions.create(
            model=model, temperature=0.3, max_tokens=max_tokens,
            messages=[{"role": "system", "content": SYSTEM},
                      {"role": "user", "content": prompt}])
        # GLM-5.2 is a reasoning model: reasoning tokens count toward max_tokens,
        # so log the split to catch truncation (finish=length means raise max_tokens).
        ch = resp.choices[0]
        u = resp.usage
        rt = getattr(getattr(u, "completion_tokens_details", None), "reasoning_tokens", None) if u else None
        print(f"  z.ai: finish={ch.finish_reason}  reasoning_tokens={rt}  "
              f"completion={getattr(u, 'completion_tokens', None)}", file=sys.stderr)
        return ch.message.content
    except Exception as e:
        # surface API errors (balance/auth/rate) with their body, not a bare traceback
        detail = getattr(getattr(e, "response", None), "text", None) or str(e)
        sys.exit(f"z.ai call failed ({model}): {detail[:500]}")


def is_mem_layout_id(s):
    import re
    return bool(re.fullmatch(r"ML\d+", s))


def read_mem_layout_algos(mem_layout):
    """experiments/sweeps/<mem_layout>.algos -> full algo names, as-is
    (the file already stores 'L1.<algo_part>' lines; comments/blanks skipped)."""
    p = os.path.join(ROOT, "experiments", "sweeps", f"{mem_layout}.algos")
    return [c.strip() for c in open(p)
            if c.strip() and not c.strip().startswith("#")]


def process_algo(algo, m, hw, model, json_only, prompt_only, force=False):
    mem_layout, algo_part = split_algo(algo)
    shash = source_hash(algo)
    # only rows pinned to the CURRENT source (drops null/stale-source rows)
    runs = load_jsonl(os.path.join(DATA, m, f"{algo}.runs.jsonl"), algo, kind="timing", source_hash=shash)
    prof = load_jsonl(os.path.join(DATA, m, f"{algo}.profile.jsonl"), algo, source_hash=shash)
    if not runs:
        print(f"  no current-source runs for {algo} — skip", file=sys.stderr)
        return "skip"
    # asm: read the bundle algo.py captured at collection time (the source of
    # truth). Build on the fly if missing (dev convenience) via algo.build_asm.
    bpath = os.path.join(DATA, m, f"{algo}.json")
    if os.path.exists(bpath):
        asm = json.load(open(bpath))["asm"]
    else:
        import algo as _algo
        print(f"  no asm bundle for {algo} — building on the fly", file=sys.stderr)
        asm = _algo.build_asm(algo, shash)
    evidence = build_evidence(algo, m, hw, runs, prof, asm)
    outdir = os.path.join(ROOT, "experiments", "analysis", m, mem_layout)
    os.makedirs(outdir, exist_ok=True)
    jpath = os.path.join(outdir, f"{algo_part}.json")
    mpath = os.path.join(outdir, f"{algo_part}.md")
    new_json = json.dumps(evidence, indent=2)
    old_json = open(jpath).read() if os.path.exists(jpath) else None
    if old_json != new_json:
        with open(jpath, "w") as f:
            f.write(new_json)
        print(f"  wrote {jpath}  ({asm['n_instructions']} insn, {len(runs)} runs)", file=sys.stderr)
    else:
        print(f"  {os.path.basename(jpath)} unchanged — skip write", file=sys.stderr)
    prompt = evidence_to_prompt(evidence)
    if prompt_only:
        print(prompt)
        return "ok"
    if json_only:
        return "ok"
    if os.path.exists(mpath) and not force:
        print(f"  {os.path.basename(mpath)} exists — skip (--force to regenerate)", file=sys.stderr)
        return "skip"
    md = llm_narrate(prompt, model)
    with open(mpath, "w") as f:
        f.write(f"<!-- auto-generated by scripts/analyze_algo.py ({model}); "
                f"source_hash={shash} -->\n\n" + md.strip() + "\n")
    print(f"  wrote {mpath}", file=sys.stderr)
    return "ok"


# ---- --verify: integrity check (narrative cites only bundle evidence) ----

SECTIONS = ["## Intent", "## Cache saturation", "## Bandwidth", "## Assembly", "## Verdict"]

# AArch64 mnemonic allowlist. A backticked token is only treated as a cited
# instruction if its base is in here — so `spawn` (a function symbol) or
# English words aren't mistaken for instructions. Keep loose; missing one just
# means a citation isn't checked, never a false flag.
MNEMONICS = frozenset("""
ldr str ldp stp ldur stur
ld1 ld2 ld3 ld4 st1 st2 st3 st4
fmov fadd fsub fmul fdiv fmla fmls fmin fmax fneg fabs fsqrt fcmp fcsel
fcvt scvtf ucvtf fcvtzs fcvtns fcvtas frintm frintp frintz
dup ext ins umov smov movi mvni ushr sshr shl usra ssra xtn
sqadd uqadd sqsub uqsub tbl tbx rev16 rev32 rev64 uzp1 uzp2 zip1 zip2 trn1 trn2
add sub mul mla mls umull smull udiv sdiv madd msub
cmp cmn tst neg mvn and orr eor bic orn lsl lsr asr ror
sbfx ubfx bfi bfxil sxth sxtw uxth uxtw sxtb uxtb adrp adr
b bl br ret cbz cbnz tbz tbnz
csel cset cinc csinc ccmp ccmn
rev clz cls rbit mov movz movk
""".split())

# Preceding-context words that mean the narrative cites an instruction's
# ABSENCE ("no `ld1` gather present") — correct, not a hallucination.
NEG_WORDS = ("no ", "not ", "without ", "absent", "absence", "zero ", "none",
             "lacks", "lack of", "neither", "nor ", "0 ")


def attested_numbers(e):
    """Every number the narrative may legitimately cite: raw values + common
    derivations (roundings; cache sizes in KB/MB; footprint in KB/MB; % of
    streaming ceiling; histogram counts)."""
    nums = set()

    def add(x):
        try:
            f = float(x)
        except (TypeError, ValueError):
            return
        for r in (3, 2, 1, 0):
            nums.add(round(f, r))
        nums.add(int(f))

    bpp = e["bytes_per_particle"]
    add(bpp)
    hw = e["hardware"]
    ceil = hw["streaming_bw_gbs"]
    for k in ("l1dcachesize", "l2cachesize", "l3cachesize",
              "cachelinesize", "logicalcpu", "streaming_bw_gbs"):
        v = hw.get(k) or 0
        add(v)
        if k.endswith("cachesize") and v:
            add(v / 1024)             # KB
            add(v / (1024 * 1024))    # MB
    for _, n in e["cache_transitions"]:
        add(n)
    for q, rows in e["series"].items():
        add(float(q))
        for r in rows:
            add(r["N"])
            add(r["ns_particle"])
            if r.get("achieved_bw_gbs") is not None and ceil:
                add(r["achieved_bw_gbs"])
                add(r["achieved_bw_gbs"] / ceil * 100)   # % of ceiling
            add(r["N"] * bpp / 1e6)          # footprint MB
            add(r["N"] * bpp / 1024)         # footprint KB
    for p in e["profile"]:
        for k in ("cycles", "compute_pct", "backend_stall_pct",
                 "frontend_stall_pct", "branch_flush_pct"):
            add(p.get(k))
    for c in e["asm"]["histogram"].values():
        add(c)
    add(e["asm"]["n_instructions"])          # "... instructions" citations
    if hw.get("cachelinesize"):
        add(hw["cachelinesize"] / 8)         # cacheline in bytes (128b -> 16B)
    return nums


def cited_mnemonics(md):
    """(base, negated) for backticked spans whose base is a real AArch64
    mnemonic. `negated` = a negation word precedes the span, i.e. the narrative
    cites the instruction's ABSENCE (correct, not a hallucination)."""
    out = []
    for m in re.finditer(r"`([^`]+)`", md):
        tok = m.group(1).strip().split()
        if not tok:
            continue
        base = re.split(r"[.\s]", tok[0])[0].lower()
        if base not in MNEMONICS:
            continue
        ctx = md[max(0, m.start() - 24):m.start()].lower()
        out.append((base, any(neg in ctx for neg in NEG_WORDS)))
    return out


def prose_numbers(md):
    """Floats + ints (>=4) from prose, with HTML comments (the glm-5.2 /
    source_hash header) and backticked spans removed."""
    s = re.sub(r"<!--.*?-->", " ", md, flags=re.S)
    s = re.sub(r"`[^`]*`", " ", s)
    s = re.sub(r"\b0x[0-9a-fA-F]+\b", " ", s)   # hex addresses (0x100055634)
    out = []
    for m in re.finditer(r"\d+\.\d+|\d+", s):
        tok = m.group()
        if "." not in tok and int(tok) < 4:
            continue
        out.append(float(tok))
    return out


def verify_algo(algo, m):
    mem_layout, algo_part = split_algo(algo)
    base = os.path.join(ROOT, "experiments", "analysis", m, mem_layout)
    jpath = os.path.join(base, f"{algo_part}.json")
    mpath = os.path.join(base, f"{algo_part}.md")
    if not os.path.exists(jpath):
        return "MISS", ["no .json bundle"], []
    if not os.path.exists(mpath):
        return "MISS", ["no .md narrative"], []
    e = json.load(open(jpath))
    md = open(mpath).read()
    errs = []
    for s in SECTIONS:
        if s not in md:
            errs.append(f"missing section {s!r}")
    hist = {k.lower() for k in e["asm"]["histogram"]}
    for b, neg in cited_mnemonics(md):
        if not neg and b not in hist:
            errs.append(f"cited instruction `{b}` not in asm histogram")
    attested = attested_numbers(e)
    unmatched = sorted({round(n, 3) for n in prose_numbers(md)
                        if not any(abs(n - a) <= max(0.05, abs(a) * 0.01) for a in attested)})
    return ("FAIL" if errs else "OK"), errs, unmatched


def run_verify(target, m, json_out=None):
    algos = [target] if not is_mem_layout_id(target) else read_mem_layout_algos(target)
    print(f"=== verify: {len(algos)} algos ===", file=sys.stderr)
    fails = 0
    results = {}
    for i, c in enumerate(algos, 1):
        status, errs, unmatched = verify_algo(c, m)
        results[c] = {"status": status, "errors": errs, "unmatched": unmatched}
        flag = {"OK": "OK  ", "FAIL": "FAIL", "MISS": "MISS"}[status]
        extra = f"  unverified_nums={unmatched[:8]}" if unmatched else ""
        print(f"[{i}/{len(algos)}] {flag} {c}{extra}", file=sys.stderr)
        for e in errs:
            print(f"           - {e}", file=sys.stderr)
        if status == "FAIL":
            fails += 1
    print(f"=== verify done: {fails} FAIL of {len(algos)} ===", file=sys.stderr)
    if json_out:
        import json as _json
        with open(json_out, "w") as f:
            _json.dump(results, f, indent=2)
        print(f"  (wrote {json_out})", file=sys.stderr)
    return 1 if fails else 0


def main():
    argv = sys.argv[1:]
    json_only = "--json-only" in argv
    prompt_only = "--prompt-only" in argv
    force = "--force" in argv
    verify_mode = "--verify" in argv
    json_out = None
    if "--verify-json" in argv:
        i = argv.index("--verify-json")
        json_out = argv[i + 1] if i + 1 < len(argv) else None
        del argv[i:i + 2]
    argv = [a for a in argv if not a.startswith("--") and not a.startswith("-")]
    target = argv[0] if argv else "ML01.AF02.LP1-autovec.LP2-opt"
    model = os.environ.get("MODEL", DEFAULT_MODEL)
    m = machine_id()
    if verify_mode:
        sys.exit(run_verify(target, m, json_out=json_out))
    hw = json.load(open(os.path.join(DATA, m, "hardware.json")))
    if is_mem_layout_id(target):
        algos = read_mem_layout_algos(target)
        print(f"=== mem_layout {target}: {len(algos)} algos (model {model}) ===", file=sys.stderr)
        ok = skip = fail = 0
        for i, c in enumerate(algos, 1):
            print(f"[{i}/{len(algos)}] {c}", file=sys.stderr)
            try:
                st = process_algo(c, m, hw, model, json_only, prompt_only, force)
                if st == "skip":
                    skip += 1
                else:
                    ok += 1
            except SystemExit as e:
                print(f"  !! FAIL {c}: {e}", file=sys.stderr)
                fail += 1
        print(f"=== done: {ok} ok, {skip} skip, {fail} fail (of {len(algos)}) ===", file=sys.stderr)
    else:
        process_algo(target, m, hw, model, json_only, prompt_only, force)


if __name__ == "__main__":
    main()
