#!/usr/bin/env python3
"""Prototype: analyze ONE algo → <algo>.json + <algo>.md.

Produces the per-algo analysis pair described in
`.scratch/plan/reporting-and-analysis.md` §2/§5 for a single algo, using:
  - <algo>.runs.jsonl  (measured timing + check rows)
  - hardware.json      (cache hierarchy + streaming ceiling)
  - <algo>.profile.jsonl (cycle attribution, if collected)
  - <algo>.json        (the asm bundle — captured disassembly of `step`, written by algo.py)

The <algo>.json is the structured evidence bundle (deterministic). The <algo>.md
is the narrative, generated by an LLM (z.ai / GLM, OpenAI-compatible) from the
evidence — Tier-2 narrative per plan decision 2.

Usage:
    scripts/analyze_algo.py ML01.AF02.LP1-autovec.LP2-opt            # full: json + md
    scripts/analyze_algo.py ML01.AF02.LP1-autovec.LP2-opt --json-only
    scripts/analyze_algo.py ML01.AF02.LP1-autovec.LP2-opt --prompt-only   # print the LLM prompt
    MODEL=glm-4.5 scripts/analyze_algo.py ML01.AF02.LP1-autovec.LP2-opt

LLM key: read from env ZAI_API_KEY, else file .scratch/zai_api_key (gitignored).
"""
from __future__ import annotations
import glob, json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sweep_config
import layout_facts

DATA = os.path.join(ROOT, "experiments", "data")
ASM_CACHE = os.path.join(ROOT, ".scratch", "asm_cache")
DEFAULT_MODEL = "glm-5.2"
ADDR = re.compile(r"^[0-9a-f]{16}$")

# The canonical naive reference every algorithm's story is told against
# (report-v2.md §0.5): AF02, loop1 scalar (de-vectorized), loop2 simple splat.
BASELINE = "ML01.AF02.LP1-scalar.LP2-simple"

# Death-rate points EXCLUDED from per-algo bundles (legacy sweep values not in
# sweep_config.DEATH_RATES). Raw data retains them. Keep in sync with
# build_report.py.
EXCLUDE_DEATH_Q = (0.0, 0.75)

# Particle counts (N) EXCLUDED from per-algo bundles — legacy sweep points
# retired from the bench SWEEP (see build_report.py). Keep in sync.
# Particle counts (N) EXCLUDED from the report. The canonical 12-point grid
# (sweep_config.CANONICAL_N_GRID) superseded the report-v2 machine-aware grids;
# these are the retired per-machine bracket points (raw data retains them).
# Plus 16000, a legacy sweep point retired earlier. Keep in sync with
# build_report.py.
EXCLUDE_N = (16000,
             380, 640, 960, 1400, 2400, 25000, 41000, 62000, 93000,       # minibits v2 grid
             320, 480, 720, 3100, 5100, 7700, 12000, 19000, 99000,       # madbits v2 grid
             160000, 250000, 370000, 620000)


def sh(cmd):
    return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True).stdout


def split_algo(algo):
    mem_layout, algo_part = algo.split(".", 1)
    return mem_layout, algo_part


def machine_id():
    import hardware_json
    return hardware_json.detect()["machine_id"]


def load_jsonl(path, algo=None, kind=None, source_hash=None):
    """Load a per-algo JSONL file. `algo`/`kind`/`source_hash` are optional row
    filters (a per-algo file is already one algo, so `algo` is usually redundant).
    `source_hash` keeps only rows pinned to the current source — drops
    pre-versioning null rows + any stale-source rows so the report never mixes
    measurement epochs. Applies EXCLUDE_DEATH_Q / EXCLUDE_N."""
    out = []
    if not os.path.exists(path):
        return out
    for line in open(path):
        try:
            r = json.loads(line)
        except Exception:
            continue
        if algo is not None and r.get("algo") != algo:
            continue
        if kind is not None and r.get("kind") != kind:
            continue
        if source_hash is not None and r.get("source_hash") != source_hash:
            continue
        if r.get("death_q") in EXCLUDE_DEATH_Q:
            continue
        if r.get("N") in EXCLUDE_N:
            continue
        out.append(r)
    return out


def source_hash(algo):
    return sh([sys.executable, os.path.join(ROOT, "scripts", "algo_hash.py"), algo]).strip()


# ---- evidence bundle ----

def cache_transitions(bpp, hw):
    out = []
    for name, key in [("L1d", "l1dcachesize"), ("L2", "l2cachesize"), ("L3", "l3cachesize")]:
        sz = hw.get(key) or 0
        if sz:
            out.append([name, sz // bpp])
    return out


def series(runs, bpp):
    """min ns/particle per (death_q, N, threads); achieved_bw = bpp·N/ns_frame."""
    best = {}
    for r in runs:
        key = (r["death_q"], r["N"], r["threads"])
        cur = best.get(key)
        if cur is None or r["ns_particle"] < cur["ns_particle"]:
            best[key] = r
    grouped = {}
    for (q, N, T), r in sorted(best.items()):
        grouped.setdefault(q, []).append({
            "N": N, "threads": T,
            "ns_particle": round(r["ns_particle"], 3),
            "ns_frame": r["ns_frame"],
            "achieved_bw_gbs": round(bpp * N / r["ns_frame"], 2) if r["ns_frame"] else None,
        })
    return grouped


# ---- references: the naive baseline + the per-(q,N,T) winner (report-v2 §3) ----
_WINNERS: dict[str, dict] = {}


def grid_minima(m):
    """{(q, N, threads): (min ns_particle, algo)} across ALL algos on machine m,
    latest source_hash per algo, EXCLUDE filters applied — the winner map."""
    if m in _WINNERS:
        return _WINNERS[m]
    latest: dict[str, str] = {}
    for p in sorted(glob.glob(os.path.join(DATA, m, "*.runs.jsonl"))):
        algo = os.path.basename(p)[: -len(".runs.jsonl")]
        for line in open(p):
            try:
                r = json.loads(line)
            except Exception:
                continue
            if r.get("kind") != "timing" or not r.get("source_hash"):
                continue
            if algo in latest and (r.get("ts_utc") or "") <= latest[algo][0]:
                continue
            latest[algo] = (r.get("ts_utc") or "", r["source_hash"])
    best: dict[tuple, tuple] = {}
    for p in sorted(glob.glob(os.path.join(DATA, m, "*.runs.jsonl"))):
        algo = os.path.basename(p)[: -len(".runs.jsonl")]
        shash = latest.get(algo, (None, None))[1]
        for line in open(p):
            try:
                r = json.loads(line)
            except Exception:
                continue
            if (r.get("kind") != "timing" or r.get("algo") != algo
                    or r.get("source_hash") != shash
                    or r.get("death_q") in EXCLUDE_DEATH_Q or r.get("N") in EXCLUDE_N):
                continue
            key = (r["death_q"], r["N"], r["threads"])
            if key not in best or r["ns_particle"] < best[key][0]:
                best[key] = (r["ns_particle"], algo)
    _WINNERS[m] = best
    return best


def baseline_minima(m):
    """{(q, N, threads): min ns_particle} for the naive baseline algo."""
    p = os.path.join(DATA, m, f"{BASELINE}.runs.jsonl")
    out = {}
    if not os.path.exists(p):
        return out
    shash = source_hash(BASELINE)
    for line in open(p):
        try:
            r = json.loads(line)
        except Exception:
            continue
        if (r.get("kind") != "timing" or r.get("source_hash") != shash
                or r.get("death_q") in EXCLUDE_DEATH_Q or r.get("N") in EXCLUDE_N):
            continue
        key = (r["death_q"], r["N"], r["threads"])
        if key not in out or r["ns_particle"] < out[key]:
            out[key] = r["ns_particle"]
    return out


def regimes(cache_transitions):
    """Band label per N given the spill transitions (report-v2 §3.1)."""
    def label(n):
        cur = "DRAM"
        for name, cut in cache_transitions:
            if n < cut:
                return f"{name}-resident"
        return cur
    return label


def asm_digest(asm):
    """Compact deterministic digest of the loop structure for the prompt."""
    if not asm or asm.get("schema") != 2:
        return None
    parts = []
    for L in asm.get("loops") or []:
        ln = f"L{L['lines'][0]}-L{L['lines'][1]}" if L.get("lines") else "?"
        if L.get("delegates"):
            s = f"loop {L['loop']} @{ln}: delegates to {L['delegates']} (external)"
        else:
            s = (f"loop {L['loop']} @{ln}: ~{L['insns']} insns/iter, "
                 f"cond-branches {L['cond_branches']}")
        if L.get("stride_bytes"):
            s += f", stride {L['stride_bytes']}B"
        if L.get("notes"):
            s += "; " + "; ".join(L["notes"])
        parts.append(s)
    for c in asm.get("calls") or []:
        if not c.get("std"):
            parts.append(f"call-delegated loop @L{c.get('line')}: {c['sym']} (external/AOT)")
    vec = asm.get("vector_insns", 0)
    tot = max(1, asm.get("n_instructions", 1))
    parts.append(f"vector-insns {vec}/{tot} across the whole step")
    return "\n  ".join(parts)


def build_evidence(algo, m, hw, runs, prof, asm):
    bpp = runs[0]["bytes_per_particle"]
    decl = {k: runs[0][k] for k in
            ("algo_fam", "ordering", "intermediates", "golden_class", "halide_expressible")}
    ct = cache_transitions(bpp, hw)
    ser = series(runs, bpp)
    # references: baseline + winner per (q,N,T), ratios folded into each row
    winners = grid_minima(m)
    baseline = baseline_minima(m)
    for q, rows in ser.items():
        for r in rows:
            key = (float(q), r["N"], r["threads"])
            bns = baseline.get(key)
            wns, walgo = winners.get(key, (None, None))
            r["baseline_ns"] = round(bns, 3) if bns is not None else None
            r["ratio_baseline"] = round(r["ns_particle"] / bns, 3) if bns else None
            r["winner"] = walgo.split(".", 1)[1] if walgo else None
            r["winner_ns"] = round(wns, 3) if wns is not None else None
            r["ratio_winner"] = round(r["ns_particle"] / wns, 3) if wns else None
    regime_of = regimes(ct)
    all_ns = sorted({r["N"] for rows in ser.values() for r in rows})
    return {
        "algo": algo, "machine_id": m,
        "source_hash": asm["source_hash"], "git_sha": runs[0].get("git_sha"),
        "mem_layout": runs[0]["mem_layout"], "bytes_per_particle": bpp,
        "algo_meta": decl,
        "hardware": {k: hw[k] for k in
                     ("cpu", "l1dcachesize", "l2cachesize", "l3cachesize",
                      "cachelinesize", "streaming_bw_gbs", "logicalcpu")},
        "cache_transitions": ct,
        "regimes": {str(n): regime_of(n) for n in all_ns},
        "memory_floor_ns": round(bpp / hw["streaming_bw_gbs"], 3),
        "layout_facts": {
            "struct": layout_facts.LAYOUTS.get(runs[0]["mem_layout"], {}).get("struct"),
            "loops": layout_facts.loop_hot_bytes(runs[0]["mem_layout"], decl["algo_fam"]),
            "intermediate_bpp": layout_facts.INTERMEDIATE_BPP.get(decl["intermediates"], 0),
        },
        "baseline": BASELINE,
        "series": ser,
        "profile": [{k: p.get(k) for k in ("N", "death_q", "threads", "trial", "profiler",
                 "cycles", "compute_pct", "backend_stall_pct",
                 "frontend_stall_pct", "branch_flush_pct")}
                for p in prof],
        "asm": asm,
        "asm_digest": asm_digest(asm),
    }


# ---- LLM narrative (z.ai, OpenAI-compatible) ----

SYSTEM = """You are a performance engineer writing the analysis for ONE algo of a \
particle-simulation benchmark, measured on ONE machine. You are given a structured \
evidence bundle: the algo's declaration, its hypothesis, the measured ns/particle \
and achieved bandwidth across N and death-rate WITH per-point references (the naive \
baseline and the best-in-grid winner at that point), the machine's cache hierarchy \
and streaming-bandwidth ceiling, the per-N cache regime labels, the memory floor \
(ns/particle at the streaming ceiling), per-loop hot-byte facts about the memory \
layout, cycle attribution (compute/backend/frontend/branch buckets), and the \
disassembly of the algo's `step` function with an instruction histogram and a \
loop digest.

The narrative's JOB is to explain WHY the algo performed the way it did on this \
hardware, anchored to the references — better/worse than naive and than the \
winner, at each N×q point, in terms of mechanisms (vectorization, branchiness, \
hot/cold byte fractions, cache spillover, the memory floor). Do NOT restate the declaration (algo_fam / ordering / intermediates / golden / loop-axes) — the \
reader already has it. Write markdown with EXACTLY these six sections, in order, \
each one a tight paragraph:

## Intent
ONE sentence: the hypothesis this algo exists to test. Start with "Hypothesis:", \
followed by a standalone sentence beginning with a capital letter. Nothing else. \
Example: "Hypothesis: A compiler auto-vectorized pass over per-particle \
components can approach the streaming ceiling on death-free workloads."

## Layout & approach
What this memory layout OFFERS the algorithm (bytes/particle, which fraction of \
them this algo's loops actually touch — the hot-byte facts — useful vs dead \
bandwidth) and what the APPROACH does about it (intermediate storage or its \
absence — verdict kept hot in registers; branchy vs blend; fusion structure), \
plus the expected interaction with the cache hierarchy (where the working set \
spills, what that means for this loop structure). This frames everything below. \
Cite the hot-byte numbers and the intermediate bytes from LAYOUT FACTS.

## Cache saturation
The ns/particle-vs-N shape, told by REGIME (each measured N carries its band \
label — L1d-resident, L2-resident, DRAM): where does cost rise at a spill, \
where is it flat, and WHY (hot fraction, prefetch friendliness, overhead \
amortization). Locate the knee relative to the transitions and say whether the \
dense grid resolves it. Do NOT walk cell by cell — speak in regimes and the \
steepest changes. Address the hypothesis here if it concerns cache behavior.

## Bandwidth
Achieved GB/s relative to the ceiling AND to the memory floor (ns/p at \
ceiling): the floor frames how much of the algo's time is irreducible memory \
time. Then the verdict — bandwidth-bound, compute-bound, branch-bound, or \
overhead-bound — and WHERE it transitions (by regime or by death rate). Ratios \
vs the baseline and the winner at the extremes and at the transition anchor \
the story: "2.3x naive at q=0.01 but only 1.1x at q=0.5 — the branchy respawn \
is the equalizer." Cite the numbers.

## Assembly
What the codegen actually did, from the loop digest + histogram + excerpt: \
vectorized or not (and across what), gather present or not, branchy respawn \
or select-based, byte-granular scatter, stride. Connect codegen to the \
bandwidth/cache findings — e.g. "component-wise vec on stride-68 explains the \
high achieved bandwidth; the scatter's byte stores cap it at 46% of ceiling." \
Cite specific instructions (e.g. `ldr q`, `fmul.4s`, `ext.16b`, `strb`).

## Verdict
Explicitly: did the hypothesis hold? Cite the two or three ratios that decide \
it (vs baseline and vs winner, at the deciding N×q points) plus the mechanism \
that explains them. Example forms:
  - "Holds — 0.9x of the winner and 3.1x faster than naive at q=0.01, \
sustaining 90% of ceiling with no cache-spill knee."
  - "Partially — beats naive everywhere (1.4-1.8x) but never beats the winner \
at q>=0.25: branch_flush rises to 36% and the select chain cannot stream."
  - "Refuted — 1.0-1.1x of naive at every point: the fused scatter's byte-granular \
writes cannot stream regardless of death rate."
One tight paragraph.

HARD RULES:
- Cite ONLY numbers and instructions present in the evidence. Never invent.
- Use the ratio/baseline/winner values given per point; do not recompute.
- If the evidence is silent on something, say so explicitly.
- No marketing voice, no "in conclusion". ~350-420 words total.
- Output ONLY the six ## sections. No preamble, no code fence."""


def evidence_to_prompt(e):
    hw = e["hardware"]
    ct = e["cache_transitions"]
    lines = [
        f"CELL: {e['algo']}",
        f"MACHINE: {e['machine_id']} ({hw['cpu']})",
        "HARDWARE:",
        f"  l1dcachesize={hw['l1dcachesize']}  l2cachesize={hw['l2cachesize']}  "
        f"l3cachesize={hw['l3cachesize']}  cachelinesize={hw['cachelinesize']}",
        f"  streaming_bw_gbs={hw['streaming_bw_gbs']}  logicalcpu={hw['logicalcpu']}",
        "CELL_DECL:",
        f"  algo_fam={e['algo_meta']['algo_fam']}  ordering={e['algo_meta']['ordering']}  "
        f"intermediates={e['algo_meta']['intermediates']}  golden={e['algo_meta']['golden_class']}",
        f"  bytes_per_particle={e['bytes_per_particle']}",
        f"  halide_expressible: {e['algo_meta']['halide_expressible']}",
        f"CACHE TRANSITIONS (working set = {e['bytes_per_particle']}·N):",
        "  " + "  ".join(f"{n} spill at N≈{v}" for n, v in ct) or "  (none)",
        f"MEMORY FLOOR: {e['memory_floor_ns']} ns/particle = bytes_per_particle / streaming_bw_gbs "
        f"— no {e['bytes_per_particle']} B/p algo can beat this on this machine.",
        f"REGIMES (band label per measured N):",
    ]
    lines += [f"  N={n} → {r}" for n, r in e["regimes"].items()]
    lf = e["layout_facts"]
    if lf.get("loops"):
        lines += ["LAYOUT FACTS:", f"  struct: {lf['struct']} ({e['bytes_per_particle']} B/particle)"]
        for i, L in enumerate(lf["loops"], 1):
            lines.append(f"  loop {i} ({'+'.join(s.capitalize() for s in L['stages'])}): "
                         f"touches {'+'.join(L['fields'])} = {L['hot_bytes']} of {L['stride_bytes']} B/p "
                         f"({int(L['hot_frac']*100)}% hot — the rest is dead weight dragged through the line filler)")
        if lf.get("intermediate_bpp"):
            lines.append(f"  intermediate storage adds {lf['intermediate_bpp']} B/particle")
        else:
            lines.append("  no intermediate storage — the death verdict stays in registers")
    lines.append(f"SERIES (min ns/particle across trials; achieved_bw = bytes/p·N / ns_frame;")
    lines.append(f"  ratios vs BASELINE={e.get('baseline')} (naive scalar) and vs WINNER (best algo on this machine at that point)):")
    for q, rows in e["series"].items():
        lines.append(f"  death_q={q}:")
        for r in rows:
            bw = f"{r['achieved_bw_gbs']} GB/s" if r["achieved_bw_gbs"] is not None else "?"
            rb = f"{r['ratio_baseline']}x baseline" if r.get("ratio_baseline") else "?"
            rw = f"{r['ratio_winner']}x winner ({r['winner']})" if r.get("ratio_winner") else "?"
            lines.append(f"    N={r['N']:<9} ns/p={r['ns_particle']:<7} achieved={bw:<12} {rb:<22} {rw}")
    if e["profile"]:
        for p in e["profile"]:
            lines.append(
                f"PROFILE (N={p['N']}, death_q={p['death_q']}, threads={p.get('threads')}, "
                f"via {p.get('profiler', '?')}): cycles={p['cycles']}  "
                f"compute={p['compute_pct']}%  backend_stall={p['backend_stall_pct']}%  "
                f"frontend_stall={p['frontend_stall_pct']}%  branch_flush={p['branch_flush_pct']}%")
    else:
        lines.append("PROFILE: (none)")
    a = e["asm"]
    lines.append(f"DISASSEMBLY of `step` ({a['n_instructions']} insns, arch {a.get('arch', '?')}), histogram:")
    lines.append("  " + "  ".join(f"{k}={v}" for k, v in a["histogram"].items()))
    lines.append(f"  vector-suffixed instructions: {a['vector_insns']}")
    if e.get("asm_digest"):
        lines.append("LOOP DIGEST (deterministic, ≈):")
        lines.append("  " + e["asm_digest"])
    lines.append("EXCERPT (full step body):")
    lines.append(a["excerpt"])
    return "\n".join(lines)


def read_key():
    k = os.environ.get("ZAI_API_KEY", "").strip()
    if k:
        return k
    f = os.path.join(ROOT, ".scratch", "zai_api_key")
    if os.path.exists(f):
        return open(f).read().strip()
    return None


def read_base_url():
    """Optional dedicated endpoint (GLM Coding Plan keys use one instead of
    the default api.z.ai). Set via env ZAI_BASE_URL or .scratch/zai_base_url."""
    v = os.environ.get("ZAI_BASE_URL", "").strip()
    if v:
        return v
    f = os.path.join(ROOT, ".scratch", "zai_base_url")
    if os.path.exists(f):
        return open(f).read().strip()
    return None


def llm_narrate(prompt, model):
    key = read_key()
    if not key:
        sys.exit("no ZAI_API_KEY in env or .scratch/zai_api_key; use --json-only/--prompt-only")
    try:
        from zai import ZaiClient
    except ImportError:
        sys.exit("zai-sdk not installed; run `uv add zai-sdk` (or `uv sync`)")
    client = ZaiClient(api_key=key, base_url=read_base_url())
    try:
        # GLM-5.2 is a reasoning model: reasoning tokens count toward
        # max_tokens. The budget varies 2k–8k reasoning + ~5k visible, so 8000
        # is too tight at the high end (a algo can finish=length with empty
        # visible output). Default 16000 leaves headroom; override per-run.
        max_tokens = int(os.environ.get("MAX_TOKENS", "16000"))
        resp = client.chat.completions.create(
            model=model, temperature=0.3, max_tokens=max_tokens,
            messages=[{"role": "system", "content": SYSTEM},
                      {"role": "user", "content": prompt}])
        # GLM-5.2 is a reasoning model: reasoning tokens count toward max_tokens,
        # so log the split to catch truncation (finish=length means raise max_tokens).
        ch = resp.choices[0]
        u = resp.usage
        rt = getattr(getattr(u, "completion_tokens_details", None), "reasoning_tokens", None) if u else None
        print(f"  z.ai: finish={ch.finish_reason}  reasoning_tokens={rt}  "
              f"completion={getattr(u, 'completion_tokens', None)}", file=sys.stderr)
        return ch.message.content
    except Exception as e:
        # surface API errors (balance/auth/rate) with their body, not a bare traceback
        detail = getattr(getattr(e, "response", None), "text", None) or str(e)
        sys.exit(f"z.ai call failed ({model}): {detail[:500]}")


def is_mem_layout_id(s):
    import re
    return bool(re.fullmatch(r"ML\d+", s))


def read_mem_layout_algos(mem_layout):
    """The sweep roster for one memory layout — sweep_config's parse of
    build.zig's algo_labels registry (the single source of truth)."""
    return sweep_config.mem_layout_algos(mem_layout)


def process_algo(algo, m, hw, model, json_only, prompt_only, force=False):
    shash = source_hash(algo)
    # only rows pinned to the CURRENT source (drops null/stale-source rows)
    runs = load_jsonl(os.path.join(DATA, m, f"{algo}.runs.jsonl"), algo, kind="timing", source_hash=shash)
    prof = load_jsonl(os.path.join(DATA, m, f"{algo}.profile.jsonl"), algo, source_hash=shash)
    if not runs:
        print(f"  no current-source runs for {algo} — skip", file=sys.stderr)
        return "skip"
    # asm: read the bundle algo.py captured at collection time (the source of
    # truth). Build on the fly if missing (dev convenience) via algo.build_asm.
    bpath = os.path.join(DATA, m, f"{algo}.json")
    if os.path.exists(bpath):
        asm = json.load(open(bpath))["asm"]
    else:
        import algo as _algo
        print(f"  no asm bundle for {algo} — building on the fly", file=sys.stderr)
        asm = _algo.build_asm(algo, shash)
    evidence = build_evidence(algo, m, hw, runs, prof, asm)
    outdir = os.path.join(ROOT, "experiments", "analysis", m)
    os.makedirs(outdir, exist_ok=True)
    jpath = os.path.join(outdir, f"{algo}.json")
    mpath = os.path.join(outdir, f"{algo}.md")
    # asm + hardware live in data/ (immutable there); strip from the on-disk
    # bundle to avoid duplication. Kept in-memory in `evidence` for the prompt.
    slim = {k: v for k, v in evidence.items() if k not in ("asm", "hardware")}
    new_json = json.dumps(slim, indent=2)
    old_json = open(jpath).read() if os.path.exists(jpath) else None
    if old_json != new_json:
        with open(jpath, "w") as f:
            f.write(new_json)
        print(f"  wrote {jpath}  ({asm['n_instructions']} insn, {len(runs)} runs)", file=sys.stderr)
    else:
        print(f"  {os.path.basename(jpath)} unchanged — skip write", file=sys.stderr)
    prompt = evidence_to_prompt(evidence)
    if prompt_only:
        print(prompt)
        return "ok"
    if json_only:
        return "ok"
    if os.path.exists(mpath) and not force:
        print(f"  {os.path.basename(mpath)} exists — skip (--force to regenerate)", file=sys.stderr)
        return "skip"
    md = llm_narrate(prompt, model)
    with open(mpath, "w") as f:
        f.write(f"<!-- auto-generated by scripts/analyze_algo.py ({model}); "
                f"source_hash={shash} -->\n\n" + md.strip() + "\n")
    print(f"  wrote {mpath}", file=sys.stderr)
    return "ok"


# ---- --verify: integrity check (narrative cites only bundle evidence) ----

SECTIONS = ["## Intent", "## Layout & approach", "## Cache saturation", "## Bandwidth", "## Assembly", "## Verdict"]

# AArch64 + x86-64 mnemonic allowlist. A backticked token is only treated as a
# cited instruction if its base is in here — so `spawn` (a function symbol) or
# English words aren't mistaken for instructions. Keep loose; missing one just
# means a citation isn't checked, never a false flag.
MNEMONICS = frozenset("""
ldr str ldp stp ldur stur
ld1 ld2 ld3 ld4 st1 st2 st3 st4
fmov fadd fsub fmul fdiv fmla fmls fmin fmax fneg fabs fsqrt fcmp fcsel
fcvt scvtf ucvtf fcvtzs fcvtns fcvtas frintm frintp frintz
dup ext ins umov smov movi mvni ushr sshr shl usra ssra xtn
sqadd uqadd sqsub uqsub tbl tbx rev16 rev32 rev64 uzp1 uzp2 zip1 zip2 trn1 trn2
add sub mul mla mls umull smull udiv sdiv madd msub
cmp cmn tst neg mvn and orr eor bic orn lsl lsr asr ror
sbfx ubfx bfi bfxil sxth sxtw uxth uxtw sxtb uxtb adrp adr
b bl br ret cbz cbnz tbz tbnz
csel cset cinc csinc ccmp ccmn
rev clz cls rbit mov movz movk
movzx movsx lea nop call jmp endbr64 vmovss vmovsd vmovups vmovaps vmovdqa vmovdqu vmovd vmovq
vmulss vmulps vmulsd vmulpd vaddss vaddps vaddsd vaddpd vsubss vsubps vsubsd vsubpd
vdivss vdivps vdivsd vdivpd vminss vminps vmaxss vmaxps vsqrtss vsqrtps
vfmadd231ps vfmadd231ss vfmadd213ps vfmadd132ps vfmadd231sd vfmadd231pd vfmsub231ps
vucomiss ucomiss comiss vbroadcastss vbroadcastps vpshufd vpshufb vpunpckldq vpunpckhdq
vinsertf128 vextractf128 vpermilps vpxor vpor vpand vcvtsi2ss vcvtsi2sd vcvtss2si vcvttss2si
vroundps vroundss cmovae cmovbe cmovne cmove cmovg cmovl cmovge cmovle sete setne
""".split())

# Preceding-context words that mean the narrative cites an instruction's
# ABSENCE ("no `ld1` gather present") — correct, not a hallucination.
NEG_WORDS = ("no ", "not ", "without ", "absent", "absence", "zero ", "none",
             "lacks", "lack of", "neither", "nor ", "0 ")


def attested_numbers(e):
    """Every number the narrative may legitimately cite: raw values + common
    derivations (roundings; cache sizes in KB/MB; footprint in KB/MB; % of
    streaming ceiling; histogram counts)."""
    nums = set()

    def add(x):
        try:
            f = float(x)
        except (TypeError, ValueError):
            return
        for r in (3, 2, 1, 0):
            nums.add(round(f, r))
        nums.add(int(f))

    bpp = e["bytes_per_particle"]
    add(bpp)
    hw = e["hardware"]
    ceil = hw["streaming_bw_gbs"]
    for k in ("l1dcachesize", "l2cachesize", "l3cachesize",
              "cachelinesize", "logicalcpu", "streaming_bw_gbs"):
        v = hw.get(k) or 0
        add(v)
        if k.endswith("cachesize") and v:
            add(v / 1024)             # KB
            add(v / (1024 * 1024))    # MB
    for _, n in e["cache_transitions"]:
        add(n)
    for q, rows in e["series"].items():
        add(float(q))
        for r in rows:
            add(r["N"])
            add(r["ns_particle"])
            if r.get("achieved_bw_gbs") is not None and ceil:
                add(r["achieved_bw_gbs"])
                add(r["achieved_bw_gbs"] / ceil * 100)   # % of ceiling
            add(r["N"] * bpp / 1e6)          # footprint MB
            add(r["N"] * bpp / 1024)         # footprint KB
            for k in ("baseline_ns", "winner_ns", "ratio_baseline", "ratio_winner"):
                add(r.get(k))
            if r.get("ratio_baseline"):
                add(1 / r["ratio_baseline"])   # "baseline is Nx slower" phrasing
                add(100 * (1 - 1 / r["ratio_baseline"]))  # %-faster-than-baseline
    add(e.get("memory_floor_ns"))
    lf = e.get("layout_facts") or {}
    for L in (lf.get("loops") or []):
        add(L["hot_bytes"])
        add(L["hot_frac"])
        add(int(L["hot_frac"] * 100))
        add(L["stride_bytes"])
    add(lf.get("intermediate_bpp"))
    a2 = e["asm"]
    for L in (a2.get("loops") or []):
        add(L["insns"])
        add(L["cond_branches"])
        add(L["vector_fp"])
        add(L["scalar_fp"])
        add(L.get("stride_bytes"))
    for p in e["profile"]:
        for k in ("cycles", "compute_pct", "backend_stall_pct",
                 "frontend_stall_pct", "branch_flush_pct"):
            add(p.get(k))
    for c in e["asm"]["histogram"].values():
        add(c)
    add(e["asm"]["n_instructions"])          # "... instructions" citations
    if hw.get("cachelinesize"):
        add(hw["cachelinesize"] / 8)         # cacheline in bytes (128b -> 16B)
    return nums


def cited_mnemonics(md):
    """(base, negated) for backticked spans whose base is a real AArch64
    mnemonic. `negated` = a negation word precedes the span, i.e. the narrative
    cites the instruction's ABSENCE (correct, not a hallucination)."""
    out = []
    for m in re.finditer(r"`([^`]+)`", md):
        tok = m.group(1).strip().split()
        if not tok:
            continue
        base = re.split(r"[.\s]", tok[0])[0].lower()
        if base not in MNEMONICS:
            continue
        ctx = md[max(0, m.start() - 24):m.start()].lower()
        out.append((base, any(neg in ctx for neg in NEG_WORDS)))
    return out


def prose_numbers(md):
    """Floats + ints (>=4) from prose, with HTML comments (the glm-5.2 /
    source_hash header) and backticked spans removed."""
    s = re.sub(r"<!--.*?-->", " ", md, flags=re.S)
    s = re.sub(r"`[^`]*`", " ", s)
    s = re.sub(r"\b0x[0-9a-fA-F]+\b", " ", s)   # hex addresses (0x100055634)
    out = []
    for m in re.finditer(r"\d+\.\d+|\d+", s):
        tok = m.group()
        if "." not in tok and int(tok) < 4:
            continue
        out.append(float(tok))
    return out


def verify_algo(algo, m):
    base = os.path.join(ROOT, "experiments", "analysis", m)
    jpath = os.path.join(base, f"{algo}.json")
    mpath = os.path.join(base, f"{algo}.md")
    if not os.path.exists(jpath):
        return "MISS", ["no .json bundle"], []
    if not os.path.exists(mpath):
        return "MISS", ["no .md narrative"], []
    e = json.load(open(jpath))
    # asm + hardware are stripped from the bundle (they live in data/); re-attach
    # for the citation/number checks below.
    e["asm"] = json.load(open(os.path.join(DATA, m, f"{algo}.json")))["asm"]
    e["hardware"] = json.load(open(os.path.join(DATA, m, "hardware.json")))
    md = open(mpath).read()
    errs = []
    for s in SECTIONS:
        if s not in md:
            errs.append(f"missing section {s!r}")
    hist = {k.lower() for k in e["asm"]["histogram"]}
    for b, neg in cited_mnemonics(md):
        if not neg and b not in hist:
            errs.append(f"cited instruction `{b}` not in asm histogram")
    attested = attested_numbers(e)
    unmatched = sorted({round(n, 3) for n in prose_numbers(md)
                        if not any(abs(n - a) <= max(0.05, abs(a) * 0.01) for a in attested)})
    return ("FAIL" if errs else "OK"), errs, unmatched


def run_verify(target, m, json_out=None):
    algos = [target] if not is_mem_layout_id(target) else read_mem_layout_algos(target)
    print(f"=== verify: {len(algos)} algos ===", file=sys.stderr)
    fails = 0
    results = {}
    for i, c in enumerate(algos, 1):
        status, errs, unmatched = verify_algo(c, m)
        results[c] = {"status": status, "errors": errs, "unmatched": unmatched}
        flag = {"OK": "OK  ", "FAIL": "FAIL", "MISS": "MISS"}[status]
        extra = f"  unverified_nums={unmatched[:8]}" if unmatched else ""
        print(f"[{i}/{len(algos)}] {flag} {c}{extra}", file=sys.stderr)
        for e in errs:
            print(f"           - {e}", file=sys.stderr)
        if status == "FAIL":
            fails += 1
    print(f"=== verify done: {fails} FAIL of {len(algos)} ===", file=sys.stderr)
    if json_out:
        import json as _json
        with open(json_out, "w") as f:
            _json.dump(results, f, indent=2)
        print(f"  (wrote {json_out})", file=sys.stderr)
    return 1 if fails else 0


def main():
    argv = sys.argv[1:]
    json_only = "--json-only" in argv
    prompt_only = "--prompt-only" in argv
    force = "--force" in argv
    verify_mode = "--verify" in argv
    json_out = None
    if "--verify-json" in argv:
        i = argv.index("--verify-json")
        json_out = argv[i + 1] if i + 1 < len(argv) else None
        del argv[i:i + 2]
    # --machine <id>: analyze THAT machine's data dir (multi-machine repos;
    # default = this host). build_report passes it per machine so `make report`
    # generates bundles for every machine with data, not just the local host.
    machine_arg = None
    if "--machine" in argv:
        i = argv.index("--machine")
        machine_arg = argv[i + 1] if i + 1 < len(argv) else None
        del argv[i:i + 2]
    argv = [a for a in argv if not a.startswith("--") and not a.startswith("-")]
    target = argv[0] if argv else "ML01.AF02.LP1-autovec.LP2-opt"
    model = os.environ.get("MODEL", DEFAULT_MODEL)
    m = machine_arg or machine_id()
    if verify_mode:
        sys.exit(run_verify(target, m, json_out=json_out))
    hw = json.load(open(os.path.join(DATA, m, "hardware.json")))
    if is_mem_layout_id(target):
        algos = read_mem_layout_algos(target)
        print(f"=== mem_layout {target}: {len(algos)} algos (model {model}) ===", file=sys.stderr)
        ok = skip = fail = 0
        for i, c in enumerate(algos, 1):
            print(f"[{i}/{len(algos)}] {c}", file=sys.stderr)
            try:
                st = process_algo(c, m, hw, model, json_only, prompt_only, force)
                if st == "skip":
                    skip += 1
                else:
                    ok += 1
            except SystemExit as e:
                print(f"  !! FAIL {c}: {e}", file=sys.stderr)
                fail += 1
        print(f"=== done: {ok} ok, {skip} skip, {fail} fail (of {len(algos)}) ===", file=sys.stderr)
    else:
        process_algo(target, m, hw, model, json_only, prompt_only, force)


if __name__ == "__main__":
    main()
