#!/usr/bin/env python3
"""Build the experiment report: read the host-partitioned JSONL data +
hardware.json, write a single experiments/report/data.parquet (read by the
duckdb-wasm page), and write the per-layout champion-grid markdown tables
into each layout README's auto-generated block (§9).

The parquet is the data the static HTML page fetches at load; duckdb-wasm
runs all SQL client-side. Re-run after every collect.

Usage:
    scripts/build_report.py                 # build data.parquet + refresh READMEs
    scripts/build_report.py --no-readme    # just the parquet
    scripts/build_report.py --no-parquet   # just the README grids (debug)
"""
import glob
import json
import os
import sys

import duckdb

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "experiments", "data")
REPORT = os.path.join(ROOT, "experiments", "report")
LAYOUTS = {"L1": "L1_aos_full"}


def load_jsonl(con, kind):
    """Register all <host>/<kind>.jsonl files into a duckdb table named <kind>."""
    paths = sorted(glob.glob(os.path.join(DATA, "*", f"{kind}.jsonl")))
    if not paths:
        return 0
    # duckdb reads jsonl directly via read_json_auto; union across hosts.
    union = " UNION ALL ".join(
        f"SELECT * FROM read_json_auto('{p}')" for p in paths
    )
    con.execute(f"CREATE TABLE {kind} AS {union}")
    return con.execute(f"SELECT count(*) FROM {kind}").fetchone()[0]


def build_parquet(con):
    """Join runs + hardware into one parquet the page fetches. achieved_bw_gbs
    is derived here (depends on the host-level streaming_bw_gbs)."""
    hw_paths = sorted(glob.glob(os.path.join(DATA, "*", "hardware.json")))
    if hw_paths:
        union = " UNION ALL ".join(
            f"SELECT * FROM read_json_auto('{p}')" for p in hw_paths
        )
        con.execute(f"CREATE TABLE hardware AS {union}")
    else:
        con.execute("CREATE TABLE hardware(machine_id VARCHAR, streaming_bw_gbs DOUBLE)")
    # runs already loaded by load_jsonl('runs').
    con.execute("""
        CREATE TABLE report AS
        SELECT r.*, h.streaming_bw_gbs,
               (r.bytes_per_particle * r.N / NULLIF(r.ns_frame, 0)) AS achieved_bw_gbs
        FROM runs r LEFT JOIN hardware h USING (machine_id)
    """)
    os.makedirs(REPORT, exist_ok=True)
    out = os.path.join(REPORT, "data.parquet")
    con.execute(f"COPY (SELECT * FROM report) TO '{out}' (FORMAT PARQUET)")
    n = con.execute("SELECT count(*) FROM report").fetchone()[0]
    print(f"  wrote {out} ({n} rows)", file=sys.stderr)
    return n


def champion_grid_sql(layout):
    """The canonical champion-grid SQL for one layout: the FASTEST cell per
    (regime, death_q). Embedded verbatim in the layout README (§9) so the
    README is self-contained; the live source is experiments/report/queries.sql."""
    return f"""-- Champion grid for {layout}: the fastest cell per (regime, death_q).
-- regime: small <=65K, mid 262K-1M, large >=4M. min ns/particle across trials.
WITH ranked AS (
  SELECT cell, death_q,
    CASE WHEN N <= 65000 THEN 'small' WHEN N <= 1000000 THEN 'mid' ELSE 'large' END AS regime,
    min(ns_particle) AS ns_particle,
    min(achieved_bw_gbs) AS achieved_bw_gbs,
    row_number() OVER (PARTITION BY
      CASE WHEN N <= 65000 THEN 'small' WHEN N <= 1000000 THEN 'mid' ELSE 'large' END,
      death_q
      ORDER BY min(ns_particle)) AS rk
  FROM report
  WHERE layout = '{layout}' AND machine_id = (
    SELECT machine_id FROM report WHERE layout='{layout}'
    GROUP BY machine_id ORDER BY count(*) DESC LIMIT 1)
  GROUP BY cell, death_q, regime
)
SELECT regime, death_q, cell,
       round(ns_particle, 3) AS ns_particle,
       round(achieved_bw_gbs, 2) AS achieved_bw_gbs,
       (SELECT streaming_bw_gbs FROM hardware LIMIT 1) AS streaming_bw_gbs
FROM ranked WHERE rk = 1
ORDER BY regime, death_q"""


def render_readme_grids(con):
    """Write the champion-grid markdown table into each layout README's
    auto-generated block (§9)."""
    for layout, folder in LAYOUTS.items():
        readme = os.path.join(ROOT, "src", "layouts", folder, "README.md")
        if not os.path.isfile(readme):
            continue
        sql = champion_grid_sql(layout)
        try:
            rows = con.execute(sql).fetchall()
            cols = [d[0] for d in con.execute(sql).description]
        except Exception as e:
            print(f"  skip {layout} README grid: {e}", file=sys.stderr)
            continue
        # Markdown table.
        lines = ["| " + " | ".join(cols) + " |",
                 "|" + "|".join(["---"] * len(cols)) + "|"]
        for r in rows:
            lines.append("| " + " | ".join(str(x) for x in r) + " |")
        block = (
            "<!-- AUTO-GENERATED by scripts/build_report.py — do not edit. -->\n"
            "## Champion grid\n\n"
            "The fastest cell per (regime, death_q), min ns/particle across "
            "trials. The canonical SQL lives in "
            "`experiments/report/queries.sql`; reproduced here verbatim so the "
            "README is self-contained:\n\n"
            "```sql\n" + sql + "\n```\n\n"
            + "\n".join(lines) + "\n"
            "<!-- /AUTO-GENERATED -->\n"
        )
        _replace_block(readme, block)
        print(f"  wrote champion grid into {readme} ({len(rows)} rows)", file=sys.stderr)


def _replace_block(path, block):
    """Replace the AUTO-GENERATED block in a README (or append if absent)."""
    text = open(path, encoding="utf-8").read()
    start = "<!-- AUTO-GENERATED by scripts/build_report.py"
    end = "<!-- /AUTO-GENERATED -->"
    if start in text and end in text:
        pre = text[: text.index(start)]
        post = text[text.index(end) + len(end):]
        text = pre + block + post
    else:
        text = text.rstrip() + "\n\n" + block
    open(path, "w", encoding="utf-8").write(text)


def main():
    no_parquet = "--no-parquet" in sys.argv
    no_readme = "--no-readme" in sys.argv
    con = duckdb.connect()
    n_runs = load_jsonl(con, "runs")
    n_checks = load_jsonl(con, "checks")
    n_pmc = load_jsonl(con, "pmc")
    print(f"loaded: {n_runs} runs, {n_checks} checks, {n_pmc} pmc", file=sys.stderr)
    if not no_parquet:
        build_parquet(con)
    if not no_readme:
        render_readme_grids(con)


if __name__ == "__main__":
    main()
